### ISSUE TITLE
Format date with 2-digits doesn't work properly on IE10

### ISSUE THREAD

**Issue by bcecchinato** [yahoo/ember-intl#101]
Hi there !

I'm using ember-intl on one of my project and found a small bug under IE10.
My hbs file is : 
```hbs
<p>{{format-date news.publicationBeginDate format="date-style"}}</p>
```

And my format.js file : 
```js
export default {
    'date-style': {
      day:  '2-digit',
      month:  '2-digit',
      year:  'numeric'
    }
};
```

I'm expecting to get a date like 01/01/2015, but when the first digit of day/month is 0, the rendered date is 1/1/2015.

I haven't found why this is only occurring on IE. I'm using the latest version (1.3.0 at the moment).

Regards,

**Comment by jasonmit** [comment]
This is a known issue in the Intl polyfill which @caridy was working on:
https://github.com/andyearnshaw/Intl.js/pull/85

I will investigate bringing this update to the polyfill over.

**Comment by caridy** [comment]
yeah, I will try to get the polyfill ready this week.

**Comment by morhook** [comment]
I'm having the same issue with latest `ember-intl@2.27.0` . Do I need to upgrade the Intl.js polyfill somehow?
