### ISSUE TITLE
Glimmer support - helpers no longer receive env

### ISSUE THREAD

**Issue by rlivsey** [yahoo/ember-intl#105]
With Glimmer in Ember Canary, helpers no longer have access to `env` and so you can no longer get the `container`.

This breaks the `intl-get` helper as it uses the container to lookup the locale etc…

There's an issue open on ember.js here: https://github.com/emberjs/ember.js/issues/11080

**Comment by jasonmit** [comment]
Thanks for letting me know.  I'll do some thinking on how to remedy this.

**Comment by elwayman02** [comment]
Yea, just saw this myself. :( Broke my upgrade to glimmer :/

**Comment by rlivsey** [comment]
The stateful helpers RFC is the current plan to resolve this - https://github.com/emberjs/rfcs/pull/53

**Comment by jasonmit** [comment]
Thanks @rlivsey I'll keep it on my radar :)  Looks very promising!

**Comment by ZenCocoon** [comment]
the latest Ember beta (upcoming 1.13.0-beta.3) have this RFC merged. However some fixes are still needed.

**Comment by ziggurat** [comment]
Using Ember 1.13 and embet-intl helpers not working. Any workaround?

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/pull/127 will address this but will be merged into the soon to be 2.0-beta1.  Be sure to look at the dummy app if you plan to use it, a few things changed and I will document them before releasing tonight or tomorrow

**Comment by jasonmit** [comment]
Fixed, part of the 2.0 branch at the moment.  Should be released as 2.0-beta1 soon.
