### ISSUE TITLE
Adding a new message programmatically for path with a non-existing parent results in error

### ISSUE THREAD

**Issue by Dremora** [yahoo/ember-intl#110]
Given the following `locales/en.js`:
```javascript
import Locale from 'ember-intl/models/locale';

export default Locale.extend({
  locale: 'en'
});
```
Doing the following:
```javascript
this.get('intl').addMessage('en', 'foo.bar', 'Foo Bar message');
```
results in an error.

Looks like something related to `Ember.Object` internals, it's only possible to set a path for which a parent object already exists.

**Comment by jasonmit** [comment]
What is the error?

**Comment by Dremora** [comment]
```
Error: Property set failed: object in path "messages.foo" could not be found or was destroyed.
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:22707:21)
    at setPath (http://localhost:4200/assets/vendor.js:26347:15)
    at Object.set (http://localhost:4200/assets/vendor.js:26272:14)
    at exports.default.mixin.Mixin.create.set (http://localhost:4200/assets/vendor.js:39876:20)
    at Ember.default.Object.extend.addMessage (http://localhost:4200/assets/vendor.js:120450:18)
    at http://localhost:4200/assets/frontend-cp.js:12388:39
    at tryCatch (http://localhost:4200/assets/vendor.js:55993:16)
    at invokeCallback (http://localhost:4200/assets/vendor.js:56005:17)
    at publish (http://localhost:4200/assets/vendor.js:55976:11)
```

**Comment by jasonmit** [comment]
This should fix your problem:

```js
export default Locale.extend({
  locale: 'en',
  messages: {}
});
```

FYI, in 2.0, `messages` will no longer be necessary.

**Comment by Dremora** [comment]
Tried it, but no luck. I have to specify all but leaf-level properties in order for it to work:
```javascript
export default Locale.extend({
  locale: 'en',
  messages: {
    foo: {}
  }
});
```

The problem is, I'm getting all strings from the API endpoint and I don't know anything about their structure. Even with the code above, trying to set `foo.bar.baz` will throw the same exception since `messages.foo.bar` is undefined.

**Comment by jasonmit** [comment]
Err, thought you had `messages.foo` as the path.  Correct, if `messages.foo.bar` you need to create `messages: { foo: {} }`.  This is just how `Ember.set` works.  You're responsible for building up the objects that don't exist as part of the path you are trying to set on.

If you don't actually want them to be objects at all but instead just treat them as strings, you're able to implement your own addMessage, getMessaeg on the locale module in which you extend from:
https://github.com/yahoo/ember-intl/blob/master/addon/models/locale.js#L12-L36

```js
// app/models/new-locale.js
import Locale from '';

export default Locale.extend({
    locale:   Ember.required(),
    messages: {},
    addMessage: function (key, value) {
        // no longer uses Ember.set!
        this.messages[key] = value;
        return value;
    },
    getValue: function (key) {
        return this.messages[key];
    }
});
````

And now your translations should extend from `app/models/new-locale.js`

**Comment by Dremora** [comment]
This solves my issue, thanks!

**Comment by jasonmit** [comment]
Excellent :)
