### ISSUE TITLE
implement instance initializer for 1.x

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#111]
Since 1.12.1 landed with instance initializers, 1.x of ember-intl should ideally implement instance-initializers

**Comment by al3x-edge** [comment]
@jasonmit I have a rough draft splitting them up for 2.0. Been working on that tonight. Not sure if it will help.  I'll work on it a bit more and get something up for you to look at it, but have a feeling I'm making a mess.

**Comment by jasonmit** [comment]
I cleaned up after your PR was merged if you wanted to take a look.  Needed to move the lookups out of `initializers` as well as that creates instances.  I also added fallback logic for users < Ember 1.12
