### ISSUE TITLE
Uncaught TypeError: message.format is not a function

### ISSUE THREAD

**Issue by aalasolutions** [yahoo/ember-intl#114]
Using Ember-CLI 0.2.6

Just installed and followed the tutorial for adding messages and locale.

`app.js` file is editied as suggested

    import Ember from 'ember';
    import Resolver from 'ember/resolver';
    import loadInitializers from 'ember/load-initializers';
    import config from './config/environment';
    
    var App;
    
    Ember.MODEL_FACTORY_INJECTIONS = true;
    
    App = Ember.Application.extend({
      modulePrefix: config.modulePrefix,
      podModulePrefix: config.podModulePrefix,
      Resolver: Resolver,
      ready: function () {
        var language = navigator.language || navigator.browserLanguage;
        this.intl.set('locales', [language, 'en']);
      }
    });
    
    loadInitializers(App, config.modulePrefix);
    
    export default App;

`locales/en.js` file is there, 

import Locale from 'ember-intl/models/locale';

    import Locale from 'ember-intl/models/locale';
    
    export default Locale.extend({
      locale: 'en',
      messages: {
        product: {
          info: '{product} Name',
          html: {
            info: '<strong>{product}</strong> Name'
          }
        }
      }
    });

in my template

    {{format-message (intl-get "messages.product")
         product='Sample'
    }}

When I load the page, it shows the page but nothing is printed for format-message and I get `Uncaught TypeError: message.format is not a function` message in the console.

**Comment by al3x-edge** [comment]
@aalasolutions Shouldn't it be like below using the `info` property?

```
{{format-message (intl-get "messages.product.info")
     product='Sample'
}}
```

**Comment by aalasolutions** [comment]
Ohh, my bad I totally overlooked it. Closing the issue

**Comment by al3x-edge** [comment]
Glad it was something simple =]
