### ISSUE TITLE
Custom formats produce different results depending on the polyfill

### ISSUE THREAD

**Issue by Dremora** [yahoo/ember-intl#115]
Not sure if this is the bug in `ember-intl` or Intl polyfill. I'm posting it here and if needed, will report upstream.

This is what I've got:

Template:
```handlebars
{{format-date date format="month"}}
```

`app/formats.js`:
```javascript
export default {
  date: {
    month: {
      month: 'long'
    }
  }
};
```

Expected output (also what I see in Chrome):
```html
June
```

Safari (using the polyfill):
```html
June 2015
```

**Comment by jasonmit** [comment]
Correct, this is a bug upstream in IntlJS polyfill.

https://github.com/andyearnshaw/Intl.js/pull/85 is attempting to solve some of the discrepancies.

**Comment by jasonmit** [comment]
Closing as this is a bug upstream and there are issues related to the the polyfill opened for tracking
