### ISSUE TITLE
Documentation is missing information on how to use custom formats

### ISSUE THREAD

**Issue by Dremora** [yahoo/ember-intl#116]
I'm guessing it's ```{{format-date date format="customFormatName"}}```.
[Documentation ends with word](http://formatjs.io/ember/#custom-formats) “The following example illustrates how these custom named formats work.”. No example is actually provided.

**Comment by jasonmit** [comment]
As part of 2.0 I will update the docs.  Let me know if you need anything explained

**Comment by jasonmit** [comment]
Also, the dummy app leverages `format` so you can look there if you need an immediate reference to how it works:
https://github.com/yahoo/ember-intl/blob/master/tests/dummy/app/formats.js
https://github.com/yahoo/ember-intl/blob/master/tests/dummy/app/templates/index.hbs#L15

**Comment by jasonmit** [comment]
Added docs to the README.md, will update the website when I get around to publishing 2.0.0-stable
