### ISSUE TITLE
When using any helper the message "env is not defined" is shown in the console

### ISSUE THREAD

**Issue by larsbs** [yahoo/ember-intl#128]
While doing a test with the library in a project, no matter what helper I use I always get the "env is not defined" message in the console and the app doesn't render at all.

The only things I've done so far are:

 1. Install the library with `ember install ember-intl`
 2. Add the `ready` function to `app/app.js` as stated in the docs
 3. Generate `en` locale with `ember g ember-intl` and then `ember g locale en`
 4. Trying to parse a number with the following helper (Previously I've tried to parse a date without success): `{{format-number product.price style="currency" currency="USD"}}`

The offending line is:
```javascript
exports['default'] = function (formatterName) {
        function throwError () {
            return new Error(formatterName + ' requires a single unname argument. {{' + formatterName + ' value}}');
        }

        if (Ember['default'].HTMLBars) {
            return function (params, hash, options, env) {
                if (!params || (params && !params.length)) {
                    return throwError();
                }

                var outStream;

                function touchStream () {
                    outStream.notify();
                }

                var value     = params[0];
                var view      = env.data.view;   // <=== ENV IS NOT DEFINED HERE
                var intl      = view.container.lookup('service:intl');
                var seenHash  = streams.readHash(hash);
                var formatter = view.container.lookup('formatter:' + formatterName);

                if (value.isStream) {
                    value.subscribe(function () {
                        touchStream();
                    }, value);
                }
// .....
```

I'm using latest version of ember-cli and Ember 1.13

UPDATE: Reading through the issues, is this related to #105?

**Comment by jasonmit** [comment]
Hi @larsbs 1.13 introduced a breaking change around how helpers are constructed.  The 1.x will only work up until 1.12.

However, there is a 2.0 branch in progress that addressed this yesterday:
https://github.com/yahoo/ember-intl/pull/127

I just need to fix the failing tests for < 1.13 before merging into 2.0.  Once that is done, I will be releasing 2.0-beta1 hopefully tonight or tomorrow.

A lot more has changed in 2.0, so if you go that route be sure to read the documentation.  The major one is translations are now stored outside of the `app` folder and in a `translations` folder and can be in YAML/JSON format.  The best example of this is in the dummy app inside of `tests`.
