### ISSUE TITLE
format-time helper is called inside conditional helper block that evaluates to false

### ISSUE THREAD

**Issue by jpaas** [yahoo/ember-intl#129]
The format-time helper fails unless you give it a valid timestamp. So I've put it inside a conditional block that should prevent it from being called when the timestamp is not present. But my template rendering fails because it calls format-time anyway. This doesn't happen with format-message.

Example, I have a form that is used for editing a model. New records don't have createdAt or updatedAt values, so I've done...

```handlebars
  {{#unless model.isNew}}
      {{input readonly=true value=(format-time model.updatedAt format='timestamp')}}
      {{input readonly=true value=(format-time model.createdAt format='timestamp')}}
  {{/unless}}
```

format-time is called whether the model isNew or not. This is with ember-intl 1.3.0.

**Comment by jasonmit** [comment]
```
{{#if lol}}
  {{input type='text' value=(format-time lol format='hhmmss')}}
{{/if}}
```

I am not able to reproduce this.  Is it possible that isNew is truthy and then flips to falsey causing the inputs to be invoked?

**Comment by jpaas** [comment]
Thanks for the suggestions. I'm implementing a master/detail view where I can select items from the master list and the detail view is rendered into an outlet using Route.render to pass the selected model to the controller. Some of those items are new and some aren't.

I tried the `{{#unless}}` and got the same results. 

I discovered that if the first item I select isNew, it renders fine. But once it renders an item that !isNew, it will never render a new one again without an error. I tried setting `{{debugger}}` and it is hit every time, except when the error occurs.

**Comment by jpaas** [comment]
Oh and if I remove the format-time from the condition, it renders fine. Its almost like some sort of timing issue where the format-time is being evaluated before the condition.

**Comment by jasonmit** [comment]
I tried reproducing it and haven't been able to.  Are you able to push your project somewhere for me to look at it build the smallest example showing the issue?

**Comment by jpaas** [comment]
https://github.com/jpaas/emberintl129

**Comment by jasonmit** [comment]
@jpaas this is no longer an issue in 2.0.0-beta.  I'm not sure I'll be able to fix it on 1.3.x

**Comment by jpaas** [comment]
Thanks @jsonmit. It took me some effort to move up to ember-intl 2.0.0-beta.5, but I can now confirm it is fixed.

**Comment by jasonmit** [comment]
Awesome, good to hear.  Let me know which portions of the upgrade were the most painful, so that I can add better docs in that area. @jpaas
