### ISSUE TITLE
Format number within a controller?

### ISSUE THREAD

**Issue by Bouke** [yahoo/ember-intl#132]
I'm trying to build a localization-aware number field as a component. Within the component I would like to format a number according to the current culture. Something like this:

```
export default Ember.TextField.extend({
    focusOut: function(event) {
        var intl = this.get('intl');
        this.set('value', intl.getNumberFormat.format(1234.5678));
    },
}
````

I tried different approaches, but none of them seem to work. How can I achieve this with ember-intl?

**Comment by jasonmit** [comment]
`Ember.TextField` is not a controller, was this example a mistake?

```js
export default Ember.TextField.extend({
    intl: Ember.inject.service(),
    focusOut: function(event) {
        var intl = this.get('intl');
        this.set('value', intl.formatNumber(1234.5678));
    }
}
```

https://github.com/yahoo/ember-intl/blob/master/addon/services/intl.js#L141-L143

**Comment by Bouke** [comment]
I'm building a component on top of TextField, so no controller's involved. Thanks so much, still trying to understand Ember's DI I guess. The hard part will be parsing the user's input back into a valid float, but Intl doesn't support that use-case sadly.
