### ISSUE TITLE
Convert to helpers to components

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#147]
`{{format-number num}}` will become `<FormatNumber value=num />`

The reasoning is to align with angle bracket components which are in the process of landing.

> Ember 2.1 will (likely) ship with angle-bracket components, which will introduce one-way data flow by default, and provide an opt-in for two-way data flow. Existing components maintain the existing behavior (for compatibility). While the internals of Ember 2.0 support a distinction between one-way and two-way bindings, that distinction will remain largely internal until Ember 2.1.

Thoughts?  If no objections I will begin to implement for ember-intl 2.1 with backwards compatibility for the foreseeable future.

**Comment by rlivsey** [comment]
Note sure about the need to do this, it seems like they are more natural as helpers and not sure what benefits would be gained by using components here.

Helpers already conform to one-way data-flow as you can't mutate values in the helper.
Converting to a component means you can't compose/use them in sub-expressions (`{{foo-bar value=(format-number num)}}`

**Comment by al3x-edge** [comment]
@jasonmit I'm also wondering about the proposed syntax with either `(intl-get value)` or the future `(icu value)` sub-expressions.

**Comment by jasonmit** [comment]
> Note sure about the need to do this, it seems like they are more natural as helpers and not sure what benefits would be gained by using components here.

Sorry it was really late when I wrote this so I didn't dive into all the reasoning.

So, my thinking was that as controllers/views go away in favor of everything components and composing a component tree similar to how you would in React, then it makes sense to begin to model ember-intl in a way that aligns with that structure.

This removes, for the majority use-case, the need for a service.  We'll still support invoking format methods via a Mixin where needed or just a thin service.  The locale will be declared from whatever you set on the application component and implicitly threaded through your component tree, similarly to how `context` works in React.

```hbs
// application/root template
<ember-intl locale=locale>
  <format-message message='product.title' />
  {{yield}}
</ember-intl>
```

There are a lot of assumptions here as we wait for >=2.0 to play out, so just spit balling an idea that may align with future Ember.

**Comment by jasonmit** [comment]
After thinking about this, I'd rather focus the next leg of feature work to align i18n and intls API so that they eventually merge can happen.
