### ISSUE TITLE
Need to display zero fractional digits for currency, but fails on Safari / polyfill/Intl.complete.js

### ISSUE THREAD

**Issue by terryroe** [yahoo/ember-intl#167]
Our application requires that we don't display the fractional portion of currency.  The default works fine when not using the polyfill.  The polyfill displays the fractional portion by default.  When I try to set maximumFractionDigits to zero, the polyfill produces the output below.  Is there a different way I should be specifying zero decimal currency values?
```
Error
column: 84
line: 1083
message: "Value is not a number or outside accepted range"
sourceURL: "http://localhost:4200/assets/intl/polyfill/Intl.complete.js"
stack: "GetNumberOption@http://localhost:4200/assets/intl/polyfill/Intl.complete.js:1083:33
InitializeNumberFormat@http://localhost:4200/assets/intl/polyfill/Intl.complete.js:1287:31
NumberFormatConstructor@http://localhost:4200/assets/intl/polyfill/Intl.complete.js:1104:34
http://localhost:4200/assets/vendor.js:85911:40
_format@http://localhost:4200/assets/my.js:7547:48
formatNumber@http://localhost:4200/assets/my.js:7516:32
http://localhost:4200/assets/my.js:5233:75
get@http://localhost:4200/assets/vendor.js:20958:30
get@http://localhost:4200/assets/vendor.js:26218:22
valueFn@http://localhost:4200/assets/vendor.js:48344:32
value@http://localhost:4200/assets/vendor.js:27297:41
read@http://localhost:4200/assets/vendor.js:27537:26
valueFn@http://localhost:4200/assets/vendor.js:27203:24
value@http://localhost:4200/assets/vendor.js:27297:41
read@http://localhost:4200/assets/vendor.js:27537:26
valueFn@http://localhost:4200/assets/vendor.js:48440:34
value@http://localhost:4200/assets/vendor.js:27297:41
read@http://localhost:4200/assets/vendor.js:27537:26
valueFn@http://localhost:4200/assets/vendor.js:27165:37
value@http://localhost:4200/assets/vendor.js:27297:41
read@http://localhost:4200/assets/vendor.js:27537:26
readArray@http://localhost:4200/assets/vendor.js:27559:20
http://localhost:4200/assets/vendor.js:27652:25
value@http://localhost:4200/assets/vendor.js:27297:41
read@http://localhost:4200/assets/vendor.js:27537:26
render@http://localhost:4200/assets/vendor.js:46729:27
EmberRenderer_createElement@http://localhost:4200/assets/vendor.js:49511:20
Renderer_renderTree@http://localhost:4200/assets/vendor.js:19036:35
ensureChildrenAreInDOM@http://localhost:4200/assets/vendor.js:50813:30
_ensureChildrenAreInDOM@http://localhost:4200/assets/vendor.js:50776:47
invokeWithOnError@http://localhost:4200/assets/vendor.js:11434:24
flush@http://localhost:4200/assets/vendor.js:11490:19
flush@http://localhost:4200/assets/vendor.js:11295:24
end@http://localhost:4200/assets/vendor.js:10720:32
http://localhost:4200/assets/vendor.js:11123:23"
```

**Comment by terryroe** [comment]
I should mention I'm using ember-intl 1.3.0.

**Comment by jasonmit** [comment]
I believe this is a duplicate of https://github.com/yahoo/ember-intl/issues/71

**Comment by jasonmit** [comment]
```hbs
{{format-number 40000.00 minimumFractionDigits=0 style="currency" currency="USD"}}
```

will output $40,000

You can read more about all the options format-number supports here https://github.com/yahoo/ember-intl/wiki/Format-Number-Options

Feel free to reopen if I misunderstood your question.

**Comment by jasonmit** [comment]
Reopening. I misunderstood your question after re-reading it.

**Comment by jasonmit** [comment]
So it appears you need to pass a `maximumFractionDigits` and a `minimumFractionDigits`

```js
var value = options[property];
// this condition line does not appear correct
if (isNaN(value) || value < minimum || value > maximum)
   throw new RangeError('Value is not a number or outside accepted range');
```

```js
// works
var Intl = require('intl');
new Intl.NumberFormat("en", { 
  maximumFractionDigits: 0, 
  minimumFractionDigits: 0, 
  style: 'currency', 
  currency: 'USD'
}).format(4000.33)
```

```js
// throws
var Intl = require('intl');
new Intl.NumberFormat("en", { 
  maximumFractionDigits: 0, 
  style: 'currency', 
  currency: 'USD'
}).format(4000.33)
```

/cc @caridy

**Comment by jasonmit** [comment]
The polyfill author says this was by design as the spec dictates it to behave this way.

**Comment by terryroe** [comment]
Jason,

Thank you very much for tracking down this answer.  I really appreciate your help!

TR

**Comment by x-yuri** [comment]
> It appears you need to pass a maximumFractionDigits and a minimumFractionDigits when dealing with the polyfill.

I suppose that is because `minimumFractionDigits` is `1` by default, so changing just `maximumFractionDigits` to `0` makes no sense.

**Comment by jasonmit** [comment]
@x-yuri awhile ago there was inconsistency between how the spec was implemented in the polyfill vs how v8 implemented `maximumFractionDigits` and `minimumFractionDigits`.

v8 has since addressed the spec misalignment and I believe the polyfill was correctly following the spec all along.

**Comment by x-yuri** [comment]
@jasonmit I'm trying to say that from your words it looks like not specifying `minimumFractionDigits` must be okay, but the spec disallows it. From what I can see, Chrome gives me this error:

![](https://i.imgur.com/dWNuUyx.png)

But it works with `maximumFractionDigits >= 2`. So supposedly `minimumFractionDigits` is `2`. That is, when you specify `maximumFractionDigits = 0`, but not specify `minimumFractionDigits`, it makes no sense. Since upper bound is lower than the lower bound.

**Comment by jasonmit** [comment]
>I'm trying to say that from your words it looks like not specifying minimumFractionDigits must be okay, but the spec disallows it.  From what I can see, Chrome gives me this error

Correct, Chrome now asserts correctly as per the spec.  In the past, this was not the case and allowed for just passing `maximumFractionDigits: 0`.

You're commenting on a very old thread where implementations have changed.

**Comment by yfrfelipe** [comment]
Just in case if someone else is facing the same issue. I got the right result with the following options:
`Intl.NumberFormat('pt-BR', { maximumFractionDigits: 2, minimumFractionDigits: 2, style: 'currency', currency: 'BRL' }).format(444.3)`
