### ISSUE TITLE
how add format options to format-message?

### ISSUE THREAD

**Issue by masciugo** [yahoo/ember-intl#178]
I'd like to do something like this:

`{{format-message (intl-get 'player.total') value=model.debit maximumFractionDigits=2}}`

where my translation is:

    player:
      total: "for a total of {value, number, EUR}"

format-number works:

`{{format-number value format='EUR' maximumFractionDigits=2}}`

**Comment by caridy** [comment]
@masciugo we can't distinguish between just key/value pairs and format settings for numbers to be formatted in a message. What if you have more than one number that you want to format in the same message? It is imposible to determine. This is why we have `formats` that you can define at the app level, which will allow you to do something like:

```
"for a total of {value, number, MyCustomFormat}"
```

where `MyCustomFormat` can be anything you want, including the `maximumFractionDigits` value for that type of number.

**Comment by caridy** [comment]
To be more specific, in ember-intl you can have a custom `app/formats.js` to define custom formats. More details here: http://formatjs.io/ember/#usage, look at the section above the usage.

**Comment by masciugo** [comment]
great. thanks a lot for your incredible effectiveness
