### ISSUE TITLE
how to set up different language and same currency?

### ISSUE THREAD

**Issue by masciugo** [yahoo/ember-intl#180]
I have 2 locales `it` and `en-us` and both of them contains the following row:

    currency: "{value, number, EUR}"

with the EUR format in my format.js:

    number: {
      EUR: { 
        style: 'currency', 
        currency: 'EUR', 
        maximumFractionDigits: 2
      }
    }

The following:

    {{format-message (intl-get 'currency') value=40}}

returns slightly different result, that is `40 €` for `it` and `€40` for `en-us`. Is this expected?

**Comment by jasonmit** [comment]
This is the locale rule for how currencies apparently are rendered in `it`. 

Validated also in Chrome's native Intl API:
`new Intl.NumberFormat('it', { style: 'currency', currency: 'EUR' }).format(40)` => `40 €`

On the polyfill, this rule can be found here: https://github.com/andyearnshaw/Intl.js/blob/master/locale-data/json/it.json#L2159-L2162

**Comment by caridy** [comment]
@masciugo just to give you more details. the value of 40 euros in english language is represented as `€40` while it is represented as `40 €`, that's about it. Thats precisely the reason you need something like ember-intl, to make sure that it gets rendered correclty.

**Comment by masciugo** [comment]
I deduce that, in respect of standards, you cannot (because you must not) make customizations mixing formats belonging to different languages. That's fair. thanks
