### ISSUE TITLE
Fails default jshint

### ISSUE THREAD

**Issue by mike-post** [yahoo/ember-intl#187]
Create a new ember application, install ember-intl, and then run ember test. You'll get the following failure: `formats.js: line 5, col 2, Missing semicolon.`

The offending code is from the `app/formats.js` blueprint:

````javascript
var hhmmss = {
  hour:   'numeric',
  minute: 'numeric',
  second: 'numeric'
} //<-- missing semicolon here

export default {
````

**Comment by jasonmit** [comment]
Thanks, will address tonight.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/0f9ea49bee32eb4e5a2ed122fab0091d72b1328e
