### ISSUE TITLE
Translation not found in tests

### ISSUE THREAD

**Issue by childss** [yahoo/ember-intl#190]
I am trying to get ember-intl working in my tests and I am getting "translation: 'message.path.here' on locale: 'en-us' was not found."

I thought that perhaps even though I followed the information in the README I was just doing something wrong so I tried checking out the example project, but that seems to have the same problem (maybe it's just out of date as well?).

Below is the relevant output from `ember test` after a clean clone of the example project and running `npm install` and `bower install`.

```
not ok 9 PhantomJS 1.9 - XProductComponent: it renders
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:2879
                at test (http://localhost:7357/assets/test-support.js:1803)
                at http://localhost:7357/assets/ember-intl-example.js:1288
                at http://localhost:7357/assets/vendor.js:150
                at tryFinally (http://localhost:7357/assets/vendor.js:30)
                at http://localhost:7357/assets/vendor.js:156
                at s (http://localhost:7357/assets/vendor.js:68616)
                at s (http://localhost:7357/assets/vendor.js:68616)
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:5651: translation: 'product.info' on locale: 'en-us' was not found.
        Log: |
    ...

not ok 14 PhantomJS 1.9 - XProductComponent: it renders
    ---
        actual: >
            null
        message: >
            Died on test #2     at http://localhost:7357/assets/test-support.js:2879
                at test (http://localhost:7357/assets/test-support.js:1803)
                at http://localhost:7357/assets/ember-intl-example.js:1363
                at http://localhost:7357/assets/vendor.js:150
                at tryFinally (http://localhost:7357/assets/vendor.js:30)
                at http://localhost:7357/assets/vendor.js:156
                at s (http://localhost:7357/assets/vendor.js:68616)
                at s (http://localhost:7357/assets/vendor.js:68616)
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:5651: Assertion Failed: A helper named 'format-message' could not be found
        Log: |
    ...
```

The "missing helper" one can be resolved by changing the `needs` in the unit test to `'helper:format-message'` at which point the error for the unit test becomes the same translation not found error.

**Comment by caridy** [comment]
can you provide the exact form that you're using to render `path.there` message?

**Comment by jsmecham** [comment]
I'm also seeing these exact errors in my project. It seems https://github.com/yahoo/ember-intl/wiki/Unit-testing-with-ember-intl is out of date for the current version of ember-intl. I've tried many incantations to try and get 'en-us' to be recognized, without success.

**Comment by childss** [comment]
Sure, although it's exactly the same as the publicly available code in [the example project](https://github.com/jasonmit/ember-intl-example). Once I get the example project working I can compare and determine any misconfiguration in my own code.

My template:
```
{{format-message (intl-get "locations.info.label")}}
```

**Comment by jsmecham** [comment]
@childss @caridy the example project fails with these same errors, fwiw.

**Comment by jasonmit** [comment]
> Once I get the example project working I can compare and determine any misconfiguration in my own code.

What is the issue with the example app that you're seeing?

> I am trying to get ember-intl working in my tests and I am getting "translation: 'message.path.here' on locale: 'en-us' was not found."

Did you manually invoke the initializer?  The initializer is responsible for registering the translation files.

https://github.com/jasonmit/ember-intl-example/blob/master/tests/unit/x-product-test.js#L14

And yes, I need to update the docs.

**Comment by childss** [comment]
> What is the issue with the example app that you're seeing?

What I posted in the initial issue text. I'm seeing the same error in both the example project and my code so I'm focused on the example project right now since that's publicly available code that's easy to point at.

To summarize: I get the "translation: 'product.info' on locale: 'en-us' was not found." error after cloning https://github.com/jasonmit/ember-intl-example and running 

```
npm install
bower install
ember test
```

I've also tried `npm cache clean` and `bower cache clean` with no difference.

**Comment by jasonmit** [comment]
@childss thanks, I completely misunderstood the issue then.  I'll fix this tonight along with the docs :+1:

**Comment by jasonmit** [comment]
https://github.com/jasonmit/ember-intl-example/pull/1/files fixes the test issue

Will close the issue once I update the docs to reflect this.  The testing strategy is different depending on ember-cli < 1.13 and >= 1.13 due to some changes Ember made around how helpers are automatically registered.

**Comment by childss** [comment]
I can confirm this fixes the example project for me as well :+1: Thanks!

**Comment by jsmecham** [comment]
Same here... Thanks!

**Comment by jasonmit** [comment]
Unit test docs updated.  Thanks for reporting!
