### ISSUE TITLE
Build error after install

### ISSUE THREAD

**Issue by dzbo** [yahoo/ember-intl#192]
After running `ember install ember-intl` I get following error:

```
ENOENT, no such file or directory '/Users/Dominik/www/test-intl/tmp/funnel-input_base_path-d6A1lVGk.tmp/0/*.js'
Error: ENOENT, no such file or directory '/Users/Dominik/www/test-intl/tmp/funnel-input_base_path-d6A1lVGk.tmp/0/*.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:792:18)
    at symlink (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:63:26)
    at Function.symlinkOrCopySync (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/node_modules/symlink-or-copy/index.js:58:5)
    at Funnel._copy (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/index.js:252:17)
    at Funnel.processFile (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/index.js:243:8)
    at Funnel.processFilters (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/index.js:154:12)
    at Funnel.build (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/index.js:118:10)
    at /Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/Dominik/www/test-intl/node_modules/ember-intl/node_modules/broccoli-funnel/node_modules/broccoli-plugin/node_modules/promise-map-series/node_modules/rsvp/dist/rsvp.js:493:16)
```

Is this something with my env? I see files at this path and can `ls` them

**Comment by caridy** [comment]
hmm, this smells. @jasonmit why do we have all those `broccoli-*` packages as `dependencies` instead of `devDependencies`? https://github.com/yahoo/ember-intl/blob/master/package.json#L35-L38

**Comment by juliankmazo** [comment]
I'm having the same error.
Those are my dependencies
```
  "devDependencies": {
    "broccoli-asset-rev": "^2.0.2",
    "connect-restreamer": "^1.0.2",
    "ember-browserify": "^1.0.0",
    "ember-cli": "^0.2.7",
    "ember-cli-app-version": "0.3.3",
    "ember-cli-babel": "^5.0.0",
    "ember-cli-bootstrap-sassy": "0.0.18",
    "ember-cli-dependency-checker": "^1.0.0",
    "ember-cli-htmlbars": "0.7.6",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-loading-slider": "^1.1.0",
    "ember-cli-qunit": "0.3.13",
    "ember-cli-sass": "^4.0.1",
    "ember-cli-uglify": "^1.0.1",
    "ember-data": "1.0.0-beta.18",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.2",
    "ember-moment": "1.1.1",
    "ember-nf-graph": "1.0.0-beta.16",
    "express": "^4.12.3",
    "glob": "^4.5.3",
    "lodash": "^3.9.1",
    "moment": "^2.10.3",
    "morgan": "^1.5.3"
  }
```

**Comment by jasonmit** [comment]
> hmm, this smells. @jasonmit why do we have all those broccoli-* packages as dependencies instead of devDependencies? https://github.com/yahoo/ember-intl/blob/master/package.json#L35-L38

They're not dev deps, they're needed for the consuming app when the consuming app is built.

https://github.com/yahoo/ember-intl/blob/master/index.js is the entry point for all addons.

The consuming ember-cli app will invoke these build hooks when the consuming app is built.  Let me know if I'm not clear.

**Comment by jasonmit** [comment]
> Is this something with my env?

Which version of ember-cli and ember-intl so I can reproduce.

**Comment by jasonmit** [comment]
I've tried to reproduce this against the example app: https://github.com/jasonmit/ember-intl-example using the latest version of ember-cli and wasn't successful.

Are any of these projects with the issue open source so I can look at them closer?

**Comment by jasonmit** [comment]
And one last thing, is this on ember-intl 1.x or 2.x?  `ember install ember-intl` will install 1.x and at this point I think it's worth using 2.x.  The only thing keeping it in beta is the docs on formatjs.io need to be updated and that's not going to be easy task unfortunately.

**Comment by juliankmazo** [comment]
I updated to 2.0.0-beta.16 and is working again. I've ember-cli 0.2.7 but I'm updating too to 1.13.8

**Comment by jasonmit** [comment]
Okay, it's been a nightmarish to support all the various versions of ember-cli and ember so I don't think I can sanely support ember-cli < 1.0.0 since I have no real way of automating testing against every version.  Ember-intl though will continue to support down to Ember 1.10.0.

Hopefully you understand!

@caridy 

What are your thoughts on pointing formatjs docs to a wiki?  I'm going to have a really hard time updating formatjs.io to work with 2.0 because the build steps are significantly more complex to get it to work with React again.  This way I can mark 2.0 as stable and then I can think about how I'll update the site to work with this release.

**Comment by dzbo** [comment]
@jasonmit 

I have `"ember-cli": "1.13.7"` and `"ember-intl": "1.3.0"` (that was default version from running `ember install`). I've updated ember-intl to `2.0.0-beta.16` and now it's okay.

**Comment by jasonmit** [comment]
Good to hear, sorry about that.  Will release as stable shortly.

**Comment by jasonmit** [comment]
1.3.1 published to fix the underlying issue originally mentioned.  Thanks to @stefanpenner :+1:

**Comment by stefanpenner** [comment]
@jasonmit who do i speak to to get commit on this repo (assuming you are ok with that)

**Comment by jasonmit** [comment]
@stefanpenner you should have write access already

**Comment by stefanpenner** [comment]
> @stefanpenner you should have write access already https://github.com/orgs/yahoo/teams/team-ember-intl

hmmm, it does look like i have access. Glitch in the matrix?

**Comment by jasonmit** [comment]
@stefanpenner elevated the group to admin of ember-intl.  Maybe that'll do it...?
