### ISSUE TITLE
ember-cli prod build with source maps fails with ember-intl

### ISSUE THREAD

**Issue by mdehoog** [yahoo/ember-intl#204]
When running `ember build -prod`, Javascript minification is enabled by default. Source maps can be enabled in `ember-cli-build.js` as follows:
```
    sourcemaps: {
      enabled: true,
      extensions: ['js']
    }
```

When running a production build of an app using `ember-intl`, the build fails with:
```
Build failed.
ENOENT, no such file or directory '/ember-app/tmp/broccoli_merge_trees-output_path-HMTQQyCi.tmp/assets/intl/Intl.js.map'
```

This is because the `Intl.js.map` is not included in the `treeForPublic()` function in `index.js`.

**Comment by elucid** [comment]
Hey there, I'm having this exact issue after upgrading to include this fix.

Here is an example repo: https://github.com/elucid/ember-intl-test

It's an empty ember-cli 1.13.8 app running ember 1.13.7 and ember-intl 2.0.0-rc.4. I've verified the correct version of ember-intl is installed and I can see the code change for the above commit in `treeForPublic()`

At the second commit (where sourcemaps are first enabled), `ember build -prod` is successful. After ember-intl is added the above error is thrown during build.

Am I missing something here?
