### ISSUE TITLE
Documentation on Pluralize?

### ISSUE THREAD

**Issue by srsgores** [yahoo/ember-intl#206]
I've been sifting through documentation, and I still do not quite understand the approach to *pluralizing* phrases.

For example:

> You have {number} unread message(s)

Where the "s" is removed when {number > 1}.

Thanks in advance for explaining.

**Comment by caridy** [comment]
@srsgores we use ICU messages, which is the standard format used in java, php, and other languages as well. Few have some user-guide around ICU messages here: http://formatjs.io/guides/message-syntax/

**Comment by caridy** [comment]
btw, more user-focused manual here: http://format-message.github.io/icu-message-format-for-translators/
