### ISSUE TITLE
Document polyfill.io usage

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#207]

**Comment by caridy** [comment]
@jasonmit I have documented some of that here: https://github.com/andyearnshaw/Intl.js#getting-started

**Comment by jasonmit** [comment]
Awesome, thanks :+1:

**Comment by jasonmit** [comment]
Updated wiki and README.md to reflect @caridy's writing

Thanks :+1:

**Comment by stefanpenner** [comment]
:+1:

**Comment by jcope2013** [comment]
can the polyfill be used with the ember-intl 1.3 series? https://github.com/yahoo/ember-intl/wiki/Intl.js-Polyfill#polyfillio

**Comment by jasonmit** [comment]
@jcope2013 yes it can

**Comment by jcope2013** [comment]
@jasonmit thanks it seems to be working in safari but issues when using it during ember test, I included the script tag in my test index.html, is it expected to work with phantom?

**Comment by jasonmit** [comment]
Interesting, can you try overriding the user agent: https://cdn.polyfill.io/v1/docs/examples#override-ua

**Comment by jcope2013** [comment]
@jasonmit will the 1.3 series update to intl 1.0.0 or just the 2.0 series? the issue I am running against that is causing my tests to fail is ``` {someDate, date, short} ``` in chrome which doesn't use the polyfill returns 8/25/15 (correct) while in safari/phantom it returns 8/25/2015 (incorrect), using intl 1.0.0 polyfill.io fixes this issue but that doesn't work in phantom,

```

ember intl 1.3.2 which has a dependency on intl: 0.1.4

var date = new Date(2015, 7, 25);
var options = { year: '2-digit', day: 'numeric', day: 'numeric' };
console.log(new Intl.DateTimeFormat('en-US', options).format(date)); 

8/25/15 // Chrome
8/25/2015 // Polyfill
```

**Comment by jasonmit** [comment]
> @jasonmit will the 1.3 series update to intl 1.0.0 or just the 2.0 series?

I can in a few days, focused currently on releasing 2.0-stable over the next day or two.
