### ISSUE TITLE
format-time tests fail due to timezone settings

### ISSUE THREAD

**Issue by zeppelin** [yahoo/ember-intl#21]
```
format-time: it should return a formatted string
Expected:  "1/23/2014"
Result:    "1/24/2014"
```

Both `dateStr` and `timeStamp` versions of the tests are affected. Replacing `GMT-0500 (EST)` with `GMT+0100 (CET)` (my local time) fixes for me - doing the reverse in an EST timezone demonstrates the issue.

Both could be fixed by adding ` timeZone="UTC"` to the template, like: 

```js
view = this.intlBlock('{{format-time "' + dateStr + '" timeZone="UTC"}}', {locales: 'en-US'});`
```

**Comment by jasonmit** [comment]
This one also bit me in ember-moment :)  I have no issue with adding timeZone to the the tests to normalize this.
