### ISSUE TITLE
2.0 Beta 19 broke my build setup, full emberApp now getting passed into environment

### ISSUE THREAD

**Issue by jcope2013** [yahoo/ember-intl#214]
this just started after updating to beta 19, a snippet of the code looks like this, i can look into creating a reproduction repo also if needed, I never had a case where environment was an object before, i always thought it be a string but I might need to adjust accordingly

```
config/environment.js

module.exports = function(environment) {
  //  environment is now an emberApp object so i have to use environment.env to 
  //  get "development" but only for ember-intl, the other times this code gets hit the 
  // environment comes in as a string as it did so in beta 18 also 

  if(environment === "development")
  { 
     console.log('test');
  }
};
```

**Comment by jasonmit** [comment]
What version of ember cli

**Comment by jcope2013** [comment]
1.13.8

**Comment by jasonmit** [comment]
Thanks, I know the cause.  Will patch in a few minutes.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/620e5f9a69b21b9950baab48e2dc07fe93daad24 versioning beta.20 now.

**Comment by jasonmit** [comment]
All fixed, thanks
