### ISSUE TITLE
top level cldrs directory being generated

### ISSUE THREAD

**Issue by rlivsey** [yahoo/ember-intl#215]
I just updated to beta.19 and now there's a `cldrs/cldrs` directory being generated in the project root containing `en.js` `en-gb.js` and `en-001.js`.

I assume these are temporary files generated from the build and shouldn't be there?

**Comment by jasonmit** [comment]
> I assume these are temporary files generated from the build and shouldn't be there?

Correct.

I've bisected and realized it happened when I updated broccoli-caching-writer from 0.5.5 to 1.0.0.

**Comment by jasonmit** [comment]
beta.21 fixes this

**Comment by rlivsey** [comment]
Great stuff, thanks
