### ISSUE TITLE
Use custom formats from formats.js from JavaScript code

### ISSUE THREAD

**Issue by terryroe** [yahoo/ember-intl#223]
Greetings,

I'm trying to determine if I can use custom formats I've specified in formats.js from JS code.  I've tried every variation I can think of to specify the custom format in a call to `this.get('intl').formatDate()`, but I haven't hit on the magic formula.  Is there a way to do this, or do I have to specify the custom format in JS, too?

Thanks,

TR

**Comment by jasonmit** [comment]
```js
// format.js
export default {
  date: {
      hour:   'numeric',
      minute: 'numeric',
      second: 'numeric'
  }
}
```

```js
// your module
import formats from 'app/formats';

this.get('intl').formatDate(date, formats.date);
```

**Comment by jasonmit** [comment]
Closing, feel free to open a new issue if this doesn't work as you are expecting.

**Comment by terryroe** [comment]
Jason,

Sorry it took me so long to respond.  Thank you for pointing me to the correct way to do this.  Much appreciated.

TR
