### ISSUE TITLE
Allow nested translations

### ISSUE THREAD

**Issue by null-null-null** [yahoo/ember-intl#224]
For addons that wish to support `ember-intl`, it would be helpful if we could nest our translations in a subdirectory of `translations`, rather than appending to the main translations files. For instance:

    /translations
      en-us.yaml
      en-gb.yaml
      /my-addon
        en-us.yaml
        en-gb.yaml

If this is something you believe `ember-intl` should support, I'll get started on a PR. I'm not super familiar with brocolli (which seems to be responsible for merging in the translations), but this could be a good learning experience.

**Comment by jasonmit** [comment]
I'm not really sure what you mean, but it does sound interesting.

You want to declare translations in your addon projects and they get merged into your application's translation files that match?

**Comment by null-null-null** [comment]
Exactly. `ember-intl` would search for any subdirectories in the translations folder and then merge them into the corresponding top-level translation files. So for instance, `translations/my-addon/en-us.yaml` gets merged into `translations/en-us.yaml`. Just to be clear, this should only merge the translations in memory. It shouldn't alter the original files.

This could also be useful for apps which want to organize their translations by page/topic. For instance:

    /translations
      en-us.yaml
      en-gb.yaml
      /blog
        en-us.yaml
        en-gb.yaml
      /reports
        en-us.yaml
        en-gb.yaml
      /commerce
        en-us.yaml
        en-gb.yaml

This way, rather than having a single massive yaml file, the developer can break their translations into more manageable chunks.

In the case of an addon, things get slightly more complicated. Since the translations folder isn't in the app directory, we can't rely on ember-cli to merge in the addon's translations for us. (Please correct me if you know of a way to do this.) Instead, the addon developer will be responsible for creating generators that'll manually populate the app's translation folder with the addon's subdirectories/translation files.

Exposing these files directly in the consuming app doesn't seem ideal, but it's the only solution I can think of.

**Comment by jasonmit** [comment]
I like the idea, go ahead with the PR.  I think it would also be good that users don't have to declare the files in the first level of the translation folder, they should be able to fully commit to organizing their translations by folder.

**Comment by jasonmit** [comment]
Great work @null-null-null.
