### ISSUE TITLE
caching-writer is old version

### ISSUE THREAD

**Issue by stefanpenner** [yahoo/ember-intl#233]
https://github.com/yahoo/ember-intl/blob/master/package.json#L25

**Comment by jasonmit** [comment]
:+1:

**Comment by jasonmit** [comment]
Are there breaking API changes between 1.1.0 and 2.x?

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/08578fa51f2efc5a6276e341329a8f93ed2c25c0 changes are here

**Comment by stefanpenner** [comment]
Why does this break an different plugin?

**Comment by jasonmit** [comment]
Not sure, didn't spend time looking into it.  Changes are on the branch and should reproduce it.

**Comment by stefanpenner** [comment]
> Not sure, didn't spend time looking into it. Changes are on the branch and should reproduce it.

If you ping me tonight, i can take a look (i will forget if not reminded :P)

**Comment by jasonmit** [comment]
Actually I bet it was npm on my box.  Will try again tonight because you're right that doesn't make sense.

**Comment by jasonmit** [comment]
af9b9a711e51412055ec50a204ab1363421ffeea
