### ISSUE TITLE
Get list of registered locales

### ISSUE THREAD

**Issue by medokin** [yahoo/ember-intl#235]
Is there a way to get a list of registered locales?

**Comment by jasonmit** [comment]
It depends on what constitutes a registered locale.  One that has translations or one that has locale data for formatting numbers, date/time, etc.?  Or both?

There isn't an API but I can give you a solution until I implement one.

**Comment by medokin** [comment]
Thanks for the offer. I think the ones that have translations. My Problem is that i don't want to hardcode a list for language selection.

**Comment by jasonmit** [comment]
```js
Object.keys(requirejs._eak_seen).filter((key) => {
  return /\/translations\/\w.?[^\/]+$/.test(key);
});
```

**Comment by jasonmit** [comment]
I'll work on exposing an API in the future

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/pull/236 will resolve this.  Adds `getLocalesByTranslations` on the service.

**Comment by jasonmit** [comment]
rc2 resolves this and is published

**Comment by medokin** [comment]
Great!
