### ISSUE TITLE
No instance.register when running integration test in Ember 2.0

### ISSUE THREAD

**Issue by mm2ha** [yahoo/ember-intl#238]
I have followed the example in the [ember-intl-example](https://github.com/jasonmit/ember-intl-example/blob/master/tests/integration/x-product-test.js) and have the following code in my integration test:
```
import hbs from 'htmlbars-inline-precompile';
import { moduleForComponent, test } from 'ember-qunit';
import Ember from 'ember';
import instanceInitializer from './../../../../../../instance-initializers/ember-intl';

moduleForComponent('devices/locks/lock-item', 'Integration | Component | devices/locks/lock item', {
    integration: true,
    setup() {
        instanceInitializer.initialize(this);
        const intl = this.container.lookup('service:intl');
        intl.set('locale', 'en-us');
    }
});
```

However, the initialization fails in ```createLocal``` function, because 
```var instance = this.container.lookup('application:main') || {}``` instance does not have ```hasRegistration```, or ```registry``` properties.

But, looking at the just ```this.container```, it has ```_registry``` property that has all the functions that seem necessary.

Is this is bug because of the current development status? I have been trying to figure this out for hours, but nothing worked, both unit and integration tests fail here.

**Comment by jasonmit** [comment]
This aspect of Ember has been constantly changing.  We have to keep doing backflips to account for all the different versions of Ember and it looks like its been changed again.

The code in question: https://github.com/yahoo/ember-intl/blob/master/addon/services/intl.js#L119-L136

/cc @mdehoog

**Comment by jasonmit** [comment]
rc3 will fix this but continuing the tradition of attempting all the various combinations to try and access the registry as I don't see a clear way to do it any other way..
