### ISSUE TITLE
Missing API documentation

### ISSUE THREAD

**Issue by nekman** [yahoo/ember-intl#239]
Hi,

We are doing some programmatically translations by using:
```javascript
const translated = this.get('intl').findTranslationByKey('some.key');
```
This works, but is this the recommended way to do a translation in a controller/component/router?
Where can we find the documentation of your public API?

**Comment by jasonmit** [comment]
> This works, but is this the recommended way to do a translation in a controller/component/router?

It sure is, and thanks for pointing out the lapse in the docs.

> Where can we find the documentation of your public API?

Feel free to submit a PR, it's certainly needed as you point out.  In general all of the "public" APIs are documented in the README + wikis (https://github.com/yahoo/ember-intl/wiki).  I do plan to extend these further in the final 2.0 release.  There has just just been a time constraint on my end for not getting 2.0 fully documented to the release, the API will not be changing at this point.

**Comment by ryrych** [comment]
What do you think of this? https://github.com/yahoo/ember-intl/wiki/Missing-API-documentation-%5BWIP%5D

I also needed that info for project so sharing that info may serve other users as well

**Comment by jasonmit** [comment]
Looks good.  Might be worth it to break the service out into its own wiki section

**Comment by jasonmit** [comment]
I created a section for services if you wanted to help out filling it https://github.com/yahoo/ember-intl/wiki/Service and one for templating https://github.com/yahoo/ember-intl/wiki/Template-Helpers

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/issues/239 and wiki articles have been bootstrapped.  Will complete over the next few days but use #239 for tracking.
