### ISSUE TITLE
Async loading breaks fallback

### ISSUE THREAD

**Issue by mjuniper** [yahoo/ember-intl#241]
I have an app that supports 26 languages. I don't want every user to have to download all 26 languages so I am trying to xhr for the user's locale and load it at runtime. 

This is what I am doing: 
````
this._fetchTranslation(translationKey)
  .then(function (translations) {
    svc.createLocale(translationKey, translations);
    svc.setLocale(translationKey);
  });
````

This works but it seems to break fallback to the `defaultLocale` (which seems to work when I just put all the locales in the /translations folder). Is this a bug, not supported, or something I'm doing wrong?

**Comment by mjuniper** [comment]
I found a workaround but it seems weird. If I include an empty file for each locale in the /translations directory and use `addTranslations` instead of `createLocale`, it works. Is there a better way?

**Comment by jasonmit** [comment]
> This works but it seems to break fallback to the defaultLocale (which seems to work when I just put all the locales in the /translations folder).

The default locale works by merging the default locale's translations into all other translations.  This happens at build time, to avoid to cost of doing this at runtime.  I think a way of keep this functionality and satisfy this requirement, I would need to write the translations, as json, to the asset folder.  This way you can async load them.  Would that work?

**Comment by mjuniper** [comment]
Awesome, thanks a bunch. Any idea on eta for 2.0?

**Comment by jasonmit** [comment]
You can track this here https://github.com/yahoo/ember-intl/issues/248

I'll try and resolve the API for addTranslations shortly.  ETA I'm aiming for is a week from today.

**Comment by jasonmit** [comment]
Sorry, I haven't forgotten about this.  I had to spend a few days to make ember-intl compatible with ember beta and canary.  I plan to get to this done by the weekend.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/pull/265 resolves this.

I've opted to not expose the translations in the assets folder, and instead allow for defining a multiple locales as your app locale.

```
intl.setLocale(['en-ca', 'en-us']);
```

When a translation is looked up, it first will look at en-ca, then en-us.  This requires you to intl.addTranslations for both locales (since you're side loading).  For those who rely on bundling the translations with the application, nothing changes.

the intl config `defaultLocale` is now also optional to improve the story where users want to opt for side loading all translations.  Previously it would throw.

I will version 2.0.0 tomorrow after I finish up some testing.

**Comment by mjuniper** [comment]
Thanks for all your work on this.

I think I'm really close to getting this working.

In `config/environment.js`, I've got:

```
intl: {
  disablePolyfill: true,
  locales: ['en-us','es'],
  defaultLocale: 'en-us'
},
```

and in my instance initializer (I tried it in beforeModel on the application route too), I've got:

```
this._fetchTranslation('es').then(resp => {
  svc.addTranslations('es', resp)
    .then(() => {
      svc.setLocale(['es', 'en-us']);
    });
});
```

But the call to `setLocale` throws "Cannot read property 'unchain' of undefined".

**Comment by jasonmit** [comment]
Can you post the stack trace

**Comment by mjuniper** [comment]
```
ChainNode.unchain	@	ember.debug.js:13529
ChainNode.remove	@	ember.debug.js:13495
unwatchPath	@	ember.debug.js:21954
unwatch	@	ember.debug.js:22015
removeDependentKeys	@	ember.debug.js:15177
ComputedPropertyPrototype.didChange	@	ember.debug.js:14610
propertyDidChange	@	ember.debug.js:19019
iterDeps	@	ember.debug.js:19126
dependentKeysDidChange	@	ember.debug.js:19077
propertyDidChange	@	ember.debug.js:19031
ChainWatchers.notify	@	ember.debug.js:13290
chainsDidChange	@	ember.debug.js:19141
propertyDidChange	@	ember.debug.js:19034
iterDeps	@	ember.debug.js:19126
dependentKeysDidChange	@	ember.debug.js:19077
propertyDidChange	@	ember.debug.js:19031
set	@	ember.debug.js:19473
setLocale	@	intl.js:154
(anonymous function)	@	i18n.js:22
fn	@	ember.debug.js:499
Queue.invoke	@	ember.debug.js:1025
Queue.flush	@	ember.debug.js:1089
DeferredActionQueues.flush	@	ember.debug.js:890
Backburner.end	@	ember.debug.js:179
Backburner.run	@	ember.debug.js:301
Backburner._runExpiredTimers	@	ember.debug.js:690
Backburner._boundRunExpiredTimers	@	ember.debug.js:145
setTimeout (async)		
Backburner._installTimerTimeout	@	ember.debug.js:746
Backburner._setTimeout	@	ember.debug.js:509
Backburner.setTimeout	@	ember.debug.js:503
run.later	@	ember.debug.js:19930
scheduledSendTree	@	VM47403:3715
Queue.invoke	@	ember.debug.js:1025
Queue.flush	@	ember.debug.js:1089
DeferredActionQueues.flush	@	ember.debug.js:890
Backburner.end	@	ember.debug.js:179
Backburner.run	@	ember.debug.js:301
run	@	ember.debug.js:19664
reset	@	VM47403:1670
start	@	VM47403:1637
appStarted	@	VM47403:7695
app.reopen.didBecomeReady	@	VM47403:7779
superWrapper	@	ember.debug.js:21572
Queue.invoke	@	ember.debug.js:1025
Queue.flush	@	ember.debug.js:1089
DeferredActionQueues.flush	@	ember.debug.js:890
Backburner.end	@	ember.debug.js:179
Backburner.run	@	ember.debug.js:301
Backburner.join	@	ember.debug.js:321
run.join	@	ember.debug.js:19706
(anonymous function)	@	ember.debug.js:19769
fire	@	jquery.js:3151
self.fireWith	@	jquery.js:3263
jQuery.extend.ready	@	jquery.js:3475
completed	@	jquery.js:3506
```

**Comment by jasonmit** [comment]
I unfortunately am not sure what is happening here, and cannot reproduce it on Ember 2.1.0 using the same code example you provided.  Is there anyway to get access to your app to step through this?  If not, can you try reproducing it with a fiddle?

**Comment by mjuniper** [comment]
Hmm, well, I can't share my code so I figured I'd create a simple app like you showed in your screenshot. Of course, it worked. So I went back to my app and banged around some more and got it working. I don't know what's actually _different_ from what I had before but it works. Thanks again.

**Comment by mjuniper** [comment]
Related to this: Is it possible to sideload the CLDR data too?

**Comment by jasonmit** [comment]
@mjuniper that will be a little bit more complex on your end but I can expose a way of doing this in the future.  Feel free to open an issue to keep it on my radar.

**Comment by mjuniper** [comment]
Thanks will do.
