### ISSUE TITLE
[Ember 2.0] Can't use `intl-get` for placeholder in `input` component

### ISSUE THREAD

**Issue by ryrych** [yahoo/ember-intl#242]
```
// placehoder evaluates to [object object]
{{input value=email placeholder=(intl-get 'auth.signUp') class='form-control'}}
```

I also tried this:

```
{{input value=email placeholder={{t 'auth.signUp'}} class='form-control'}}
```

but ember-cli can't compile it.

Using it in normal (not a component) input works as expected:

```
<input type='text' value='' placeholder={{t 'auth.signIn'}}>
```

**Comment by rlivsey** [comment]
@ryrych The `intl-get` helper returns the translation object, not the final string.

You can use the `t` helper to get a translated string, as you used on the non-component input, so the following should work:

```handlebars
{{input value=email placeholder=(t 'auth.signUp') class='form-control'}}
```

**Comment by jasonmit** [comment]
Thanks @rlivsey :)

**Comment by ryrych** [comment]
Cool, thanks!
