### ISSUE TITLE
formatMessage + findTranslationByKey...combined API?

### ISSUE THREAD

**Issue by elwayman02** [yahoo/ember-intl#243]
It seems that `this.get('intl').formatMessage(this.get('intl').findTranslationByKey('foo.bar'))` is a not uncommon use-case. Perhaps this scenario warrants a method that can do both internally with a more user-friendly DSL? Or is there an easier way already and we missed it?

**Comment by jasonmit** [comment]
I would be open to review a PR to implement a `t` function on the service.

**Comment by elwayman02** [comment]
:+1: will look into this tomorrow probably
