### ISSUE TITLE
Restrict number of localization copied files ember-intl 1.3

### ISSUE THREAD

**Issue by Jcamilorada** [yahoo/ember-intl#246]
Hey

I am trying to restrict the ember localization copied files. Addin this lines into my environments file as described https://github.com/yahoo/ember-intl/wiki/Intl.js-Polyfill#cherry-pick-cldr-modules. Without success. Is this feature supported on 1.3 any workaround? 

intl: { locales: ['en-us', 'en-gb', 'fr-fr'] }

**Comment by jasonmit** [comment]
This feature is not available in 1.13, and I really recommend upgrading to 2.0.  The only thing holding 2.0 back from being released is documenting more of the complicated APIs.  The majority of the cases are documented.
