### ISSUE TITLE
Documentation on how to include ember-intl in test suite

### ISSUE THREAD

**Issue by terryroe** [yahoo/ember-intl#25]
It would be very helpful to have some documentation showing how to use ember-intl in ember-cli tests.  I currently get messages like this when running my tests:
```
Handlebars error: Could not find component or helper named 'format-relative'
Handlebars error: Could not find component or helper named 'intl-get'
```
In order to get past these, I stubbed out these methods in my setup method  like this:
```
    component = this.subject();
    // stubs for ember-intl
    component.intl = {};
    component['format-relative'] = component.intl.get = function (str) {
      return str;
    };
```
But I would rather know how to include the library in the test suite.

Thanks.

TR

**Comment by jasonmit** [comment]
Unit testing may be a problem, acceptance shouldn't be.  

I'll think of a way to best solve this, perhaps by creating a utility function you would need to invoke in the setup hook of your unit test.  Would that be acceptable?

**Comment by terryroe** [comment]
The above problems I ran into were in unit tests for components.  It would be nice if there were a better way to stub things out, but I can live with my approach for now.  A utility function for setup would be great.  Thanks.

**Comment by jasonmit** [comment]
With my latest changes (1.1.0), it's a little bit easier.  Assuming you are on 1.10:
https://github.com/yahoo/ember-intl/blob/master/tests/unit/format-date-test.js#L13-L14

You'll always want to register an intl:main into the Container.  

```
import Intl from 'app/services/intl';

// in your setup
container.register('intl:main", Intl, { instantiate: true, singleton: true });
```

**Comment by jasonmit** [comment]
#77 will resolve this. Feel free to test the branch out and follow the changeset in the new README.

Let me know if I should expand on anything further.

**Comment by jasonmit** [comment]
1.3.0 released today, which resolves some testing concerns.

Also, here is a pretty simply test seeing if a component including format-message rendered: https://github.com/jasonmit/ember-intl-1.3.0-test-example
