### ISSUE TITLE
can't get ember integration tests running with 2.0.24 beta

### ISSUE THREAD

**Issue by maladon** [yahoo/ember-intl#250]
...and the doc for the test pages is blank.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/wiki are not blank

> ...and the doc for the test pages is blank.

What are you referencing?

**Comment by maladon** [comment]
On the home page there are two links to unit testing and integration testing. (here's one: https://github.com/yahoo/ember-intl/wiki/Integration-testing-with-ember-intl). When you click those it takes you to a "create new page" form. 

I hadn't looked at the wiki since that page seems to have most of what's needed. Maybe it should link to the wiki instead? I see now that the wiki answers my questions.
