### ISSUE TITLE
Default for format-date helper?

### ISSUE THREAD

**Issue by drewclauson** [yahoo/ember-intl#253]
Is there a way to specify the default format for format-date?

For example, whenever I do:
```{{format-date model.invoiceDate }}```

I'd like it to do this by default:
```{{format-date model.invoiceDate month='2-digit' day='2-digit' year='numeric'}}```

A step further, is there a way to specify a default format for a specific locale?

Thanks!

**Comment by jasonmit** [comment]
> I'd like it to do this by default

Not entirely, but it's possible where you do not have to pass each attribute and instead just a `format` attribute. This is documented here: https://github.com/yahoo/ember-intl#named-formats

**Comment by drewclauson** [comment]
Thanks! - one more question, if I use the formatting option in a different locale (i.e. I want to use mm/dd/yyyy in en-us but de-DE is dd.MM.yyyy), will it still format it as mm/dd/yyyy when the locale is de-DE?

**Comment by jasonmit** [comment]
> if I use the formatting option in a different locale

Your example here doesn't require multiple formats, it would be just one:

```js
// app/formats.js
export default {
  date: {
    custom: {
      month: '2-digit',
      day: '2-digit',
      year: 'numeric'
    }
  }
};
```

`{{format-date some-date format='custom'}}`

en would return mm/dd/yyyy
de-de would return dd.mm.yyyy

**Comment by jasonmit** [comment]
Feel free to reopen if you have any related questions.

**Comment by drewclauson** [comment]
Thanks!!

**Comment by drewclauson** [comment]
One more question, if I wanted to display the date in YYYY-MM-DD format for en-US, how would I do that?

Thanks!

**Comment by sbsurf** [comment]
I have the same question - for dates + date/times I need to be able to use the ISO format of `YYYY-MM-DD`. Ideally, with AM/PM vs 24 hr option set automatically based on locale.

**Comment by drewclauson** [comment]
@sbsurf Since I was the OP, I wanted to just comment that I don't recall if I ever figured that out.  Unfortunately, I no longer am on the project that utilized this, so I can't go back and look at the code.  Sorry!

**Comment by sbsurf** [comment]
Thanks @drewclauson. This was more a question for someone like @jasonmit. Didn't want to open another issue, so I piggy-backed onto yours.

**Comment by jasonmit** [comment]
@sbsurf I would refer to the Intl.DateTimeFormat API:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

This is the browser primitive used under the hood.  All options there are what we support.

The 24hr (`hour12` options) is locale dependent by default so you should not have to touch that unless you want to override for specific locales.

Formatting is dictated by what the locale rules suggest.

**Comment by sbsurf** [comment]
Thanks @jasonmit. I actually want to force that date format for any locale. If you can think of a way to override it, let me know. I'll keep poking.
