### ISSUE TITLE
`translation.has` does not work for nested translation keys

### ISSUE THREAD

**Issue by elwayman02** [yahoo/ember-intl#255]
See: https://github.com/yahoo/ember-intl/blob/master/addon/models/translation.js#L49

Because it uses the native `hasOwnProperty`, this method has no way to actually check if an embedded key exists (for example, `errors.blank`). 

```
let obj = Ember.Object.create({ foo: { bar: 'baz' } });
obj.hasOwnProperty('foo') // true
obj.hasOwnProperty('foo.bar') // false
```

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/d23209cb270cf52e37a0ba749329ecbb2d5ec9e2
