### ISSUE TITLE
format-relative expect timestamp in milliseconds

### ISSUE THREAD

**Issue by sammy007** [yahoo/ember-intl#259]
Is there any way to avoid this requirement and format timestamps in seconds using ember-intl? Please consider this ticket as feature request if it's impossible yet, it's definitely not ok to change backend to return milliseconds or multiply timestamps by 1000 on client.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/wiki/Format-Relative-Options units accepts `second` as an argument.  

And format-relative invokes the `Date` constructor, which handles number of milliseconds since 1 January, 1970 UTC.

https://github.com/yahoo/ember-intl/blob/e85296063a042a5336794a437bc6c831ca61c73c/addon/formatters/format-relative.js#L28

**Comment by sammy007** [comment]
> units accepts second as an argument.

This is not relevant.

> And format-relative invokes the Date constructor, which handles number of milliseconds since 1 January, 1970 UTC.

There are thousands APIs which return timestamp as number of seconds. Why not make an option to specify that timestamp is in seconds similar to "units" option?

**Comment by jasonmit** [comment]
I'm skeptical as to how useful adding support for this would be when the Date constructor doesn't even appear to support value in as an argument.  Out of curiosity, how do you normal handle your dates on the client?

**Comment by sammy007** [comment]
If Date ctor expect only milliseconds it's Date ctor's problems and API developers should not all start to return milliseconds. I propose fromUnits="m | s | ms | ?" option, before passing argument to ctor multiply by 60000, 1000, etc.

**Comment by jasonmit** [comment]
I still don't feel this is a common scenario and prefer this be handled outside of ember-intl.  A quick solution below, but still recommend you normalize your seconds->ms at the serializer level as you'll always run into issues given that `Date` doesn't accept seconds.

```js
// app/helpers/seconds-to-ms.js
export default Ember.Helper.extend({
  compute(params) {
    return params[0] * 1000;
  }
});
```

```hbs
{{format-relative (seconds-to-ms value)}}
```
