### ISSUE TITLE
Uncaught Error: format-message helper requires value

### ISSUE THREAD

**Issue by anthonycollini** [yahoo/ember-intl#260]
Fresh install with this addon and a simple translation key produces the following error:
`Uncaught Error: format-message helper requires value`

The template looks like `{{t 'advertiser'}}`.

In my en-us.yaml, I have:
`advertiser: 'test'`

I have the beforeModel and environment config set up per doc instructions.

    "ember-intl": "2.0.0-rc.5",
    "ember-cli": "1.13.12",
    "ember": "2.1.0",

Thoughts on how to get around or fix this?

**Comment by jasonmit** [comment]
Can you push a project with the issue isolated, it will speed up turn around time.

**Comment by anthonycollini** [comment]
So I created a brand new ember app, and it seems to work fine. However, this ember app is being loaded into a rails project using ember-islands and ember-cli-rails, which is perhaps the issue. Do you know of any conflicts that would occur between these libraries? Does ember-intl need access to routes, or the router that ember-islands turns off? Let me know if you have any thoughts.

**Comment by jasonmit** [comment]
I unfortunately know nothing about ember-island and little about ember-cli-rails.  I will keep the issue opened in hopes someone comes around to help triage.

> Does ember-intl need access to routes, or the router that ember-islands turns off?

Nope, ember-intl does not interact with the routes at all.

**Comment by anthonycollini** [comment]
Okay, so here is the issue, and I don't know why I didn't realize it before...

ember-intl does use routes, because it calls the service in the application route in the beforeModel hook to setLocale. Ember Islands removes routes completely.

So to get around this, I created an instance initializer that loads it when the app boots up.

    // instance-intializers/ember-intl-locale.js
    export function initialize(application) {
      let intl = application.lookup('service:intl');
      intl.setLocale('en-us');
    }

    export default {
      name: 'ember-intl-locale',
      initialize
    };

**Comment by jasonmit** [comment]
> ember-intl does use routes, because it calls the service in the application route in the beforeModel hook to setLocale.

ember-intl itself doesn't use routes.  I provide an example of how you might set your applications locale using the application route.  However, you're entirely correct that it can also be done using an initializer.

Thanks for coming back and updating the issue, I'm sure it will be helpful for future travelers :+1:
