### ISSUE TITLE
issue with npm v3

### ISSUE THREAD

**Issue by stefanpenner** [yahoo/ember-intl#261]

**Comment by jasonmit** [comment]
Whats the issue?

**Comment by jasonmit** [comment]
https://github.com/ef4/ember-code-snippet/pull/14/files should resolve this

**Comment by stefanpenner** [comment]
sorry, meant to post more info. https://github.com/ef4/ember-code-snippet/pull/14 was the issue I noticed, unsure if there were more after or not.

**Comment by jasonmit** [comment]
After I resolved code snippet everything worked as expected.  Closing for now feel free to reopen if you see any other issues

**Comment by stefanpenner** [comment]
:)
