### ISSUE TITLE
Add support for `PLN` currency symbol: `zł`

### ISSUE THREAD

**Issue by artsyca** [yahoo/ember-intl#272]
Steps to reproduce

`{{format-number 99.99 style='currency' currency='PLN'}} => PLN99.99`

Expected:

`zł99.99` 

ref: https://en.wikipedia.org/wiki/Polish_z%C5%82oty

**Comment by jasonmit** [comment]
This is the expected behavior with the `en` locale.

Native IntlJS API (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat):

```js
new Intl.NumberFormat('pl', { style: 'currency', currency: 'PLN' }).format(100); // => 100,00 zł
```

en as the locale, PLN as the currency:
```
new Intl.NumberFormat('en', { style: 'currency', currency: 'PLN' }).format(100); // => PLN100.00
```

**Comment by devinus** [comment]
@jasonmit Is there any way to add currency symbols to an already loaded locale?
