### ISSUE TITLE
is version 2 the recommended version?

### ISSUE THREAD

**Issue by Jcamilorada** [yahoo/ember-intl#273]
Hey

I just check the commits and I am happy to see that version 2 has been released, checking formatJs [page](http://formatjs.io/ember/) version 1.3.0 is still displayed in ember guide. Is there any issue related to migration?, is version 2.0 recommended for production environments?.

**Comment by jasonmit** [comment]
2.0 is the recommended version, I have an issue opened to remove ember-intl live docs from formatjs.io since it's time consuming to port ember-intl to work within the sites environment (react).

https://github.com/yahoo/formatjs-site/issues/201
