### ISSUE TITLE
Not testing with setup instanceInitializer in Component integration test

### ISSUE THREAD

**Issue by richardvenneman** [yahoo/ember-intl#275]
I'm trying to test a component which formats a message based on a property. I've setup the integration test as per [the wiki documentation](https://github.com/yahoo/ember-intl/wiki/Testing---Integration), but once I complete the instructions, no tests are being run anymore.

Component code:
```javascript
import Ember from 'ember';

export default Ember.Component.extend({
  intl: Ember.inject.service(),

  output: Ember.computed('key', function() {
    let key = `output.${this.get('key')}`
    
    return this.get('intl').formatMessage(key/*, optional options hash */);
  })
});
```

Test code:
```javascript
import hbs from 'htmlbars-inline-precompile';
import { moduleForComponent, test } from 'ember-qunit';
import instanceInitializer from '../../instance-initializers/ember-intl';

moduleForComponent('x-test', 'Integration | Component | x test', {
  integration: true,
  setup() {
    // manually invoke the ember-intl initializer
    instanceInitializer.initialize(this);
    const intl = this.container.lookup('service:intl');
    intl.setLocale('en-us');
  }
});

test('it renders', function(assert) {
  // Set any properties with this.set('myProperty', 'value');
  // Handle any actions with this.on('myAction', function(val) { ... });"

  this.render(hbs`{{x-test key='test'}}`);

  assert.equal(this.$('.output').text().trim(), 'Awesomeness');
});
```

Output after I add the instanceInitializer setup:

<img width="818" alt="screen shot 2016-01-17 at 12 26 10" src="https://cloud.githubusercontent.com/assets/75705/12377209/8314c55c-bd15-11e5-9cc0-dbf297c220a2.png">

Output without the instanceInitializer setup (commented out `instanceInitializer` import statement and `moduleForComponent` `setup()` block):

<img width="818" alt="screen shot 2016-01-17 at 12 27 49" src="https://cloud.githubusercontent.com/assets/75705/12377211/c0666c26-bd15-11e5-9967-94f55e4ccc22.png">

Quite new to Ember, am I missing something?

I've also setup an example repo: https://github.com/richardvenneman/ember-intl-test.

Example repo:

- ember-cli 2.2.0-beta.6
- ember 2.2.0
- ember-intl 2.0.0

But I'm also experiencing this in my ember-cli 1.13.13 project.

**Comment by jasonmit** [comment]
When you run it in the browser, do you see a stacktrace?  If so, can you paste it here.

**Comment by jasonmit** [comment]
I sent a PR into ember-intl-test to show you how to resolve this https://github.com/jasonmit/ember-intl-test/commit/45515d2a0c7a4ff676cd98e842a21eb94e507d30 

If there are inefficiencies in ember-intl docs that made this confusing, please edit the wiki or send a PR in to change the README.

**Comment by richardvenneman** [comment]
Thanks for the quick reply; great stuff, works perfectly. Will make the edits tonight!

**Comment by jasonmit** [comment]
:+1: thanks.  Easier to gather feedback from fresh eyes since I tend to glance over any missing parts

**Comment by richardvenneman** [comment]
Done. Yeah I totally understand. Gotta say however the docs are great and easy to follow! For newbies as well :grinning:
