### ISSUE TITLE
format-number with computed property

### ISSUE THREAD

**Issue by BenjaminHorn** [yahoo/ember-intl#276]
```javascript
{{format-number 10 style='currency' currency='USD'}}

{{row.defaultPrice.price}}
```

this gives:
```javascript
10,00 US$ 
13
```

But 
```javascript
{{format-number row.defaultPrice.price style='currency' currency='USD'}}
```
gives
> Uncaught Error: format-number helper requires value

`row` is a record and `defaultPrice` is a computed property on it.

**Comment by jasonmit** [comment]
Can you verify that this works if row isn't a record?  This may be a nuance with dealing with PromiseObjects

**Comment by jasonmit** [comment]
The original value is likely undefined and later the record loads and the binding is reevaluated.  The only thing I can do to support this is add an allow empty flag where if value is ever undefined return undefined.  This may fix your issue.

**Comment by BenjaminHorn** [comment]
@jasonmit 
> Can you verify that this works if row isn't a record?

this works fine:
```hbs
{{format-number price.defaultPrice.price style='currency' currency='USD'}}
<!-- 20,00 US$  -->
```
where
```javascript
var test = Ember.Object.extend({
  defaultPrice: Ember.computed('price', function(){
    var price = this.get('price');
    return {price: price};
  })
});

export default Ember.Controller.extend({
  price: test.create({price: 20})
});
```

In my first example `defaultPrice` is a CP depends on a promise (relationship)
```javascript
import DS from 'ember-data';
import Ember from 'ember';

export default DS.Model.extend({
  // ...
  defaultPrice: Ember.computed('servicePrices', function(){
    var defaultPrice = null;
    this.get('servicePrices').forEach((price) => {
      if (price.get('default')) {
        defaultPrice = price;
        return false;
      }
    });
    return defaultPrice;
  })
});
```

**Comment by jasonmit** [comment]
Okay, I am pretty sure it's the fact the relationships is returning a PromiseObject.  I'll need to think about how to solve this one.

**Comment by jasonmit** [comment]
Through the public API, Ember.Helper's compute method only receives `undefined` when a PromiseObject's promise hasn't resolved.  I could use private APIs to work around that, but for now opted for all helpers to optionally except an `allowEmpty` argument.  What this does is cause a noop if the promise hasn't resolved.  When the promise does eventually resolve, the helper will automatically recompute on its own.  I ran some tests and verified this resolves the above issue.

`{{format-number price.defaultPrice.price style='currency' currency='USD' allowEmpty=true}}`

The fix is in 2.0.1.

**Comment by BenjaminHorn** [comment]
Great, thanks! Could you please npm publish it?

**Comment by jasonmit** [comment]
Oops, just published it to npm now -- was exhausted and forgot last night.

**Comment by BenjaminHorn** [comment]
@jasonmit  Thanks, great patch!

This works nicely: 
```javascript
{{format-number row.defaultPrice.price style='currency' currency='USD'}}
```
but 

```javascript
{{format-number row.defaultPrice.price style='currency' currency=row.defaultPrice.currency.iso}}
```
gives 

>Uncaught TypeError: Currency code is required with currency style.

and raises a bunch of Deprecation warnings but the same time it renders correctly

`3,00 DOP`

`currency` is a relationship (promise) on `defaultPrice`.

**intl-format-cache/memoizer**
```javascript
    function createFormatCache(FormatConstructor) {
        var cache = (0, _intlFormatCacheEs5.objCreate)(null);

        return function () {
            var args = Array.prototype.slice.call(arguments);
            var cacheId = getCacheId(args);
            var format = cacheId && cache[cacheId];

            if (!format) {
                // error here:
                format = new (_intlFormatCacheEs5.bind.apply(FormatConstructor, [null].concat(args)))(); 

                if (cacheId) {
                    cache[cacheId] = format;
                }
            }

            return format;
        };
    }
```
