### ISSUE TITLE
Problems with initial setup

### ISSUE THREAD

**Issue by riklaunim** [yahoo/ember-intl#282]
I'm trying to setup ember-intl with ember 2.3 and I have few problems.

http://formatjs.io/ember/ writes about adding 
```
ready: function () {
        this.intl.set('locales', ['en-US']);
    }
```

while this.intl isn't available there. Also "locale" doesn't shows up as valid blueprting for locale generation with ember-cli. I have the app/formats.js and those two demo translation files, but something is missing somewhere.

**Comment by makepanic** [comment]
Have you tried to use the `intl` service? 
The example from the [github README](https://github.com/yahoo/ember-intl#setting-runtime-locale) works for me:

```js
  // app/routes/application.js
  export default Ember.Route.extend({
    intl: Ember.inject.service(),
    beforeModel() {
      // define the app's runtime locale
      // For example, here you would maybe do an API lookup to resolver
      // which locale the user should be targeted and perhaps lazily
      // load translations using XHR and calling intl's `addTranslation`/`addTranslations`
      // method with the results of the XHR request
      //
      this.get('intl').setLocale('en-us');

      // OR for those that sideload, an array is accepted to handle fallback lookups

      // en-ca is the primary locale, en-us is the fallback.
      // this is optional, and likely unnecessary if you define defaultLocale (see below)
      // The primary usecase is if you side load all translations
      this.get('intl').setLocale(['en-ca', 'en-us']);
    }
  });
```

The blueprint for creating new dummy translations is `ember g translation de-de` (see https://github.com/yahoo/ember-intl/tree/master/packages/ember-intl/blueprints/translation).
Aside from the `translation` and default `ember-intl`, there is no blueprint (check `ember g --help` for a list of all commands).

**Comment by jasonmit** [comment]
@riklaunim the documentation on formatjs is old and I created an issue to remove it.  Please use the README and wiki articles on github.

https://github.com/yahoo/formatjs-site/issues/201

**Comment by jasonmit** [comment]
I've submitted a PR to remove the documentation from formatjs.io to avoid this confusion.
