### ISSUE TITLE
Translations for a dropdown

### ISSUE THREAD

**Issue by ajgordo** [yahoo/ember-intl#287]
I need to provide a dropdown that contains a list of translated values where the key will be what is stored in to a model. (e.g. a list of statuses where the status id is what is send back to the the server).
Is there an easy way to achieve this?

Thanks in advance.

**Comment by jasonmit** [comment]
```hbs
<select onChange={{action 'handleSelection' value='target.value'}}>
  <option disabled='disabled' selected></option>
  <option value='foo'>{{t 'foo'}}</option>
  <option value='bar'>{{t 'bar'}}</option>
</select>
```

**Comment by jasonmit** [comment]
Sorry, feel free to close if this answers you question.

**Comment by ajgordo** [comment]
Thanks. That's along the lines. But I'm thinking more in an each loop to get all statuses available.

**Comment by jasonmit** [comment]
```hbs
<select onChange={{action 'handleSelection' value='target.value'}}>
  <option disabled='disabled' selected></option>
  {{#each items as |item|}}
    <option value={{item.value}}>{{t item.key}}</option>
  {{/each}}
</select>
```

So do the following

**Comment by ajgordo** [comment]
This is not what I'm talking about it exactly.
If I had translations in a json file, e.g.
{ 
  statuses: {
    0: ready
    1: nearly ready
    2: not ready
  }
}
How would I use that as the "items" you had above? The findTranslationByKey won't do it, so I'm wondering if there is another way?

**Comment by jasonmit** [comment]
You can use `translationsFor` to get all the translations for a locale

https://github.com/yahoo/ember-intl/blob/master/packages/ember-intl/addon/services/intl.js#L155-L165
