### ISSUE TITLE
Drop `defaultLocale` in favor of iterating `locales` array?

### ISSUE THREAD

**Issue by ericf** [yahoo/ember-intl#29]
I just saw this comment by @caridy: https://github.com/yahoo/react-intl/issues/76#issuecomment-73143477 and it spurred a thought that Ember Intl could simply iterate over the `locales` array to find the default/fallback locale. This would make `defaultLocale` config/prop not needed.

**Comment by jasonmit** [comment]
@ericf I kind of like having them separate, otherwise the consumer will need to be cognizant of keeping the default locale at the tail of the locales array.

This is currently the implementation for ember-intl:
```js
// pseudo-code but it's pretty similar
getMessage: function (path) {
  var locales = Ember.makeArray(this.locales);
  locales.push(this.defaultLocale); // in the actual implementation I don't push if locales contains the defaultLocale
  for(var i=0;i<locales.length;i++) {
    var locale = this.getLocaleObject(locales[i]);
    var msg = locale.get(key);
    if (typeof msg !== 'undefined') { return msg; }
  }
}
```

**Comment by ericf** [comment]
This the way `locales` is suppose to work as a fallback anyways, so I think it fits. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#Locale_negotiation

**Comment by jasonmit** [comment]
Ah, that makes sense.  I'll remove it

**Comment by ericf** [comment]
> Ah, that makes sense. I'll remove it. Do you want me to update the other libs while I'm at it?

Let's discuss it first. That's why I cc'd @caridy

**Comment by jasonmit** [comment]
The result of the chat offline was to remove references to `defaultLocale` and then remove it from the code base when we remove it from all the other integration libs.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/issues/67 supersedes this
