### ISSUE TITLE
Are you prefer using helper or computed property?

### ISSUE THREAD

**Issue by Exelord** [yahoo/ember-intl#294]
What is preferred way by you to use translations with params? Eg:
Should I add a line in template:
``` hbs
{{t 'task.placeholders.byCreator' name=model.creator.displayName}}
```

or should I chose computed property and then use it in template:
``` es6
creatorName: Ember.computed('model.creator.displayName', function() {
    let label = this.get('model.creator.displayName');
    return this.get('intl').i18n('task.placholders.byCreator', { name: label });
  }),
```

and then

``` hbs
{{creatorName}}
```

**Comment by jasonmit** [comment]
Good question, I definitely lean more towards using the helper versus a cp.

**Comment by ryrych** [comment]
For me it depends and it is more generic than intl itself. If *computation* is more complex I'd prefer the latter; otherwise the former. I'd use the gut feeling. :)
