### ISSUE TITLE
Add support for flat json structure 

### ISSUE THREAD

**Issue by uitgewis** [yahoo/ember-intl#296]
The current implementation does not seem to allow for flat-style keys.

Example:
```
{
    "login.authenticate": "Authenticate",
    "login.forgot-password": "Forgot Password"
}
```

It would be nice if ember-intl could detect this flat structure and parse them into something usable.
Currently, using a flat structure as per above causes Ember throw an error for not finding the parent key when it attempts to break it down:
```
Error: Property set failed: object in path "login" could not be found or was destroyed.
```

**Comment by jasonmit** [comment]
Originally discussed here but the implementation is slightly different on 2.x: https://github.com/yahoo/ember-intl/issues/110#issuecomment-107017737

`addMessage` is now `addTranslation` and `locale.js` is now `translation.js`

https://github.com/yahoo/ember-intl/blob/master/packages/ember-intl/addon/models/translation.js#L31-L38

That said, auto-detecting probably is an unlikely feature I'll implement but I'd be happy to implement a blueprint for those who rely on dots in their translations which will override the default implementation.

**Comment by jasonmit** [comment]
Can you give this branch a try https://github.com/yahoo/ember-intl/pull/297

`ember g ember-intl-dot-notation` and it should take over the default implementation

**Comment by jasonmit** [comment]
I validated it, merging and will document before versioning

**Comment by jasonmit** [comment]
Versioned as 2.5.0 and updated the README

**Comment by uitgewis** [comment]
Thanks @jasonmit, I initially worked around the issue by having the initial file being read (the base file) as an expanded json structure, which made the properties available for the rest of the translations.

But I'll definitely try/use this. Again, thanks for the quick response!
