### ISSUE TITLE
Still need Bower?

### ISSUE THREAD

**Issue by ericf** [yahoo/ember-intl#30]
Do you still need Bower for Ember CLI add ons?

**Comment by jasonmit** [comment]
Yeah, it's baked into ember cli based on why I mentioned above.  I would love for this to not be the case.



—

**Comment by jasonmit** [comment]
Er on my phone and thought I was on the formatjs thread :). 

Right now ember cli addons require bower mainly because Ember itself does not have a modern npm build (it's about two years old).  I imagine this will change now that there are efforts to render ember on the server.

**Comment by davglass** [comment]
Can the `postinstall` at least be removed? It's really a bad practice (not to mention very annoying) to have a postinstall on a module that installs something else, in this case a pile of bower modules. Is that the common practice with Ember?

**Comment by jasonmit** [comment]
`ember install:addon` should remove the need for it, so I can remove it now.
