### ISSUE TITLE
DEPRECATION: Using `ApplicationInstance.container.lookup` is deprecated. Please use `ApplicationInstance.lookup` instead. 

### ISSUE THREAD

**Issue by jcope2013** [yahoo/ember-intl#301]
DEPRECATION: Using `ApplicationInstance.container.lookup` is deprecated. Please use `ApplicationInstance.lookup` instead. [deprecation id: ember-application.app-instance-container] See http://emberjs.com/deprecations/v2.x/#toc_ember-applicationinstance-container for more details.
 
Ember 2.4.3
Ember Intl 2.6.0

related to this line

https://github.com/yahoo/ember-intl/commit/56c8e069fb8226d004db9254a30c878e3bfd00d3#diff-82f1798f3c0da0d474fbaea34b74515bR18

**Comment by jasonmit** [comment]
@jcope2013 good catch, did the deprecation warning start in 2.6.0?

**Comment by jasonmit** [comment]
Opened a PR to resolve this, waiting for CI to finish and then will version as 2.6.1

**Comment by jasonmit** [comment]
Published as 2.6.1
