### ISSUE TITLE
Allow fallback value for format helpers

### ISSUE THREAD

**Issue by buschtoens** [yahoo/ember-intl#303]
```hbs
{{! someNumber = undefined }}
My value: {{format-number someNumber style="percent" fallback="-"}}
``` 
```html
My value: -
```

It would be great, if we could define fallback strings for `undefined` values.

If this would be welcome, I'd be glad to submit a PR. :smiley:

**Comment by jasonmit** [comment]
I'm in favor of this, and would love if you spiked a PR

**Comment by buschtoens** [comment]
Awesome. While looking through the code I came across these lines:

```js
    compute(params, hash = {}) {
      const value = this.getValue(params, hash);
      const allowEmpty = getWithDefault(hash, 'allowEmpty', helperOptions.allowEmpty);

      if (isEmpty(value) && allowEmpty && hash.fallback === undefined) { return; }

      if (typeof value === 'undefined') {
        throw new Error(`format-${formatType} helper requires value`);
      }

      // ...
    },
```

Is there a specific reason, why we first check for [`isEmpty`](https://github.com/emberjs/ember.js/blob/v2.4.0/packages/ember-metal/lib/is_empty.js#L4) (which checks for [`isNone`](https://github.com/emberjs/ember.js/blob/v2.4.0/packages/ember-metal/lib/is_none.js#L1)) and then again check for `undefined`?

If not, I'd restructure the code like this:

```js
    compute(params, hash = {}) {
      let value = this.getValue(params, hash);
      const allowEmpty = getWithDefault(hash, 'allowEmpty', helperOptions.allowEmpty);

      if (isEmpty(value)) {
        if (hash.fallback) {
          value = hash.fallback;
        } else if(allowEmpty) {
          return;
        } else {
          throw new Error(`format-${formatType} helper requires value`);
        }
      }

      // ...
    }

**Comment by jasonmit** [comment]
I'm unsure if I'm following but I'll try to answer.  If `allowEmpty` is set to true and the passed in value is empty, return an empty string.  Otherwise, throw an Error.

**Comment by buschtoens** [comment]
Yes, of course. WTF was I thinking? Haha :joy:   
Expect a PR today. :)

**Comment by jasonmit** [comment]
Looking forward :+1:

**Comment by jasonmit** [comment]
Versioned as 2.7.0, thanks again :+1:
