### ISSUE TITLE
2 tests failing due to timezone

### ISSUE THREAD

**Issue by buschtoens** [yahoo/ember-intl#304]
![image](https://cloud.githubusercontent.com/assets/834636/14029300/94ddc150-f201-11e5-81c6-8aff4154306b.png)

While working on my PR I found out that, two tests fail due to timezone differences. My timezone is CET (Europe/Berlin). Setting it to something US-ish fixes the issue.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/416aebb5035cc2825694bfe3fa8e082581ad9ae7 should do it

**Comment by jasonmit** [comment]
Actually, reopening my fix isn't going to fix the issue.
