### ISSUE TITLE
Linting is not linting...

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#33]
Likely a bug in ember-cli, but I need to do some investigating and send a PR to fix the issue.

Opening in an issue for tracking.

**Comment by zeppelin** [comment]
Well, `.jshintrc` is obviously missing from the repo. But even after I added it back with the below (ember-cli default) content, it didn't seem to help.

```json
{
  "predef": [
    "document",
    "window",
    "-Promise"
  ],
  "browser": true,
  "boss": true,
  "curly": true,
  "debug": false,
  "devel": true,
  "eqeqeq": true,
  "evil": true,
  "forin": false,
  "immed": false,
  "laxbreak": false,
  "newcap": true,
  "noarg": true,
  "noempty": false,
  "nonew": false,
  "nomen": false,
  "onevar": false,
  "plusplus": false,
  "regexp": false,
  "undef": true,
  "sub": true,
  "strict": false,
  "white": false,
  "eqnull": true,
  "esnext": true,
  "unused": true
}
```

**Comment by jasonmit** [comment]
:) that will do it.  Just saw the same thing.  I'll fix it now

**Comment by zeppelin** [comment]
Argh, silly me. Once already there, could you bump `ember-cli-qunit` to `0.3.4`? :)
Almost 100% sure it'll fix the issue.

**Comment by jasonmit** [comment]
:+1:

**Comment by zeppelin** [comment]
Linting got extracted from the ember-cli main since 0.1.10: https://github.com/ember-cli/ember-cli/pull/3122

**Comment by jasonmit** [comment]
All fixed

**Comment by zeppelin** [comment]
Wonderful :+1: thank you!
