### ISSUE TITLE
RFC: "ember-lazy-intl" - explore wrapping this addon for lazy loading

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#41]
While lazy loading is possible today, it takes some implementing on the consumers part to get right.  You can read more about the general implementation: https://github.com/yahoo/ember-intl/issues/18#issuecomment-74393002

--

This proposal is to bake the most likely use case, where you want to lazy load from the asset tree your locales.  

This should not be part of ember-intl directly, and instead be an addon which wraps ember-intl.  This is because it makes a really bold assumption as to how people store & load their messages and would only overcomplicate ember-intl if implemented directly. 

* [ ] Opt out of walking app/locales/*.js to extract the CLDR data to allow for side loading CLDR data
* [ ] Locales should continue to extend from `ember-intl/models/locale` but not concatted into app.js and instead written to `/assets/locales/<locale-name>.js`
* [ ] When a locale is registered it needs to `addLocaleData` https://github.com/yahoo/ember-intl/blob/e28f857b6ea897216cac0bd2aa803fa42c181606/addon/utils/data.js#L10
* [ ] Should not load locales which are already loaded

/cc @bakura10

**Comment by bakura10** [comment]
Definitely sounds like the right approach to the problem! thanks a lot for your work on this, it makes usage much better ;)

**Comment by gigafied** [comment]
Even if we didn't go so far as an addon, just the right hooks would be sufficient. Currently, you can side load messages into a Locale at runtime, but there is no way to side-load the CLDR or create Locales at runtime that aren't baked in during build.
