### ISSUE TITLE
Verify can pass format-intl values as attrs

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#47]
I know this won't be possible in 1.9 due to the SimpleView being returned but could likely be possible in 1.10.

This issue is to verify and track and issues.

/cc @mutewinter

**Comment by jasonmit** [comment]
Verified 1.10 works fine with bind-attr:

```hbs
<button {{bind-attr title=(format-message (intl-get 'messages.foo'))}}>Test title</button>
```

**Comment by mutewinter** [comment]
Awesome! This was a blocker for us switching from Ember I18n
