### ISSUE TITLE
Deprecate Ember 1.9.x

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#56]
It's complicating the design to support both Handlebars/HTMLBars.  Since the features for ember-intl 1 is more or less complete, now is a good time to deprecate 1.9.

**Comment by jasonmit** [comment]
This relates also to #52 where each version of ember-intl will be versioned against the current stable version of ember.  I will also entertain maintaining patch versions in between for the more recent versions behind "current"

**Comment by jcope2013** [comment]
I am on ember 1.9 at the moment, is it correct that 1.2.2 still supports 1.9 and the changes to not support 1.9 are on master at the moment?

**Comment by jasonmit** [comment]
Correct, master is not 1.2.2.  1.2.2 continues support for 1.9.

I tag all my releases in git, https://github.com/yahoo/ember-intl/tree/1.2.2

2.0 will no longer support handlebars, in favor of just supporting htmlbars.

**Comment by jcope2013** [comment]
thanks, also can you use the handlebar subexpressions with 1.9, cant seem to get it work, i know one of the big points of htmlbars (1.10) is it allows subexpressions, but has format-message/format-html-message ever worked with 1.9?

```
{{format-html-message (intl-get 'messages.product.html.info')
```
