### ISSUE TITLE
Custom date format not being used in format-message

### ISSUE THREAD

**Issue by rlivsey** [yahoo/ember-intl#58]
I've added a custom date formatter to simply display the short form of a week-day, but that doesn't seem to be being used in a message. It's working with `format-date` but not with `format-message`.

Here's [an example repo](https://github.com/rlivsey/ember-intl-test) containing an Ember app with the code below:

Eg:

```javascript
export default {
  date: {
    shortWeekDay: {
      weekday: "short"
    }
  }
};
```

This is then used in a message:

```javascript
import Locale from 'ember-intl/models/locale';

export default Locale.extend({
  locale: 'en',
  messages: {
    test: "should be a week-day initial: {day, date, shortWeekDay}"
  }
});
```

When displaying this in a template I'd expect the same date format to be shown:

```handlebars
<p>format-date: {{format-date date format="shortWeekDay"}}</p>
<p>format-message: {{format-message (intl-get "messages.test") day=date}}</p>
```

But instead I get the following:

![screenshot 2015-02-23 20 24 41](https://cloud.githubusercontent.com/assets/3740/6336369/11aadfd2-bb9a-11e4-9b21-98c79a2b8091.png)

**Comment by rlivsey** [comment]
FWIW - I'm seeing the same thing happen with time formats too, `{{format-time}}` works fine, but using the same custom format in `{{format-message}}` doesn't work.

**Comment by jasonmit** [comment]
You're absolutely correct, they should be returning the same results.  I'll do some digging tonight as to what is going on.

**Comment by jasonmit** [comment]
Ah, found the problem.  So `day` is more or less a "reserved" format option.  I should probably document this somewhere, so I'll keep it opened as a bug.  But good news is no patch is needed to get this to work.

`{{format-message '{dayOfWeek, date, shortWeekDay}' dayOfWeek=yesterday}}`

**Comment by jasonmit** [comment]
1.1.4 published which will resolve this

**Comment by rlivsey** [comment]
Awesome, thanks. Trust me to pick a reserved word for my first experiment!

**Comment by rlivsey** [comment]
Just updated to 1.1.4 and can confirm this resolves the issue in my app. Thanks.
