### ISSUE TITLE
intl.get(messageKey) doesn't work in non-template code

### ISSUE THREAD

**Issue by terryroe** [yahoo/ember-intl#60]
Ember 1.10.0, ember-intl 1.1.1

Console output
```
$E.intl.get('messages.phone')
undefined
$E.intl.get
ember.debug.js:32014 function (keyName) {
        return get(this, keyName);
      }
```
The above message key "messages.phone" does exist and is output correctly via template code.  Trying to use intl.get() in a component or from the browser console (the above example used the ApplicationControler as $E) always returns 'undefined'.

**Comment by jasonmit** [comment]
That's using the Ember.get accessor.  The `intl-get` handlebar helper is not the same `this.intl.get`

Are you trying to just access the a locale's message object directly?

It would be this: `$E.intl._getLocaleInstance('en').get('messages')`

The service doesn't expose this in any sort of API that behaves like `intl-get`, which walks over all the "active" locale(s) and stops at the first one that has the key.

**Comment by terryroe** [comment]
I was trying to do a message lookup, thinking there was an analogous function to the intl-get helper.  It seems like this is needed if you want to be able to retrieve locale message strings in code in order to be able to format them with formatMessage.  Could a function like this be added?  Is there more information I could provide?

**Comment by jasonmit** [comment]
For the sake of not blocking you until I publish another release, you can move these two functions an Ember.Mixin and then you'll get the behavior you're looking for.  https://github.com/yahoo/ember-intl/blob/master/app/helpers/intl-get.js#L9-L33

**Comment by terryroe** [comment]
Thanks Jason.  We're still in heavy development, so we can wait for the next published release.  I used your suggested code from your first response as a temporary fix just to get things working.  Thanks for being so responsive and helpful.  It's much appreciated.

**Comment by jacojoubert** [comment]
This would be a great addition. I will move it to a mixin for now.

**Comment by jasonmit** [comment]
1.2.0 resolves this: https://github.com/yahoo/ember-intl/blob/master/app/services/intl.js#L192-L206

`this.intl.getTranslation(key)` just note that it returns a promise to handle potential future changes to lazily load translations by default.
