### ISSUE TITLE
Consume new "slimmed-down" CLDR dep

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#61]
Keeping this opened for tracking.

/cc @ericf

**Comment by jasonmit** [comment]
Ready for consuming: https://github.com/yahoo/formatjs-extract-cldr-data

Assigning to myself to implement

**Comment by ericf** [comment]
PR yahoo/grunt-extract-cldr-data#2 is related.

**Comment by ericf** [comment]
The slimmed down version is now ~14MB as it now only contains the CLDR data files that are needed to supply the data to the FormatJS libs.

**Comment by jasonmit** [comment]
1.2.0 resolves this
