### ISSUE TITLE
Remove subscription to the application locale

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#65]
I've been following @caridy's discussions on this topic in another thread where he makes the case that subscribing to locale changes to trigger a rerender of the component/helper is not a common pattern.

For example, if the users changes their locale at runtime, any helpers rendered after the change will receive the new locale change.  Anything rendered previously will stay rendered on the previous locale.  Handling this  really complicates the helper logic and there is overhead in subscribing to those changes for each and every helper.

The workaround would be recommending users to reload the view explicitly using a `rerender` where they need to immediately reflect the change.

Unfortunately, we cannot begin removing this yet because the application view is not able to rerender.   This is demonstrated here http://jsbin.com/ruzuho/1/edit?html,js,console,output (click rerender twice, observe the console while doing so).  So, until that bug is fixed within Ember we cannot resolve this issue.

/cc @caridy

**Comment by caridy** [comment]
When you mean workaround, you mean removing those listeners, and rely on some sort of best practice (doc) to explain that they should re-render manually?

Can you link to the corresponding ember issue?

**Comment by jasonmit** [comment]
> When you mean workaround, you mean removing those listeners, and rely on some sort of best practice (doc) to explain that they should re-render manually?
Correct.  Remove the listeners and provide documentation for the < 80% use case.

The issue: https://github.com/emberjs/ember.js/issues/2267 looks like it was closed but has regressed if it was in fact fixed at some point.

**Comment by caridy** [comment]
Ok, :+1:

**Comment by jasonmit** [comment]
Spoke to Paul (@tchak13) and he currently does an app destroy and recreates to work around this issue.  We can implement the same pattern and document it as a work around for the 1% case where consumers want to change the locale at runtime.

**Comment by jasonmit** [comment]
Will keep this around now that the new Ember.Helper better supports the usecase.
