### ISSUE TITLE
Unable to lookup the "intl:main" service in unit tests

### ISSUE THREAD

**Issue by mordack** [yahoo/ember-intl#76]
At the moment I'm unable to write unit tests for components that use of the ```format-message``` and ```intl-get``` helpers in the component template.

Initially, this is what I've tried when just setting the test up:
```
needs: [
  'locale:en-GB', 'helper:format-message', 'helper:intl-get'
]
```
This results in an exception when calling ```this.render()``` in the actual tests:
```TypeError: Cannot read property 'on' of undefined```, the stacktrace points to [this](https://github.com/yahoo/ember-intl/blob/master/app/helpers/intl-get.js#L45) line. Which makes sense as ```'intl:main'``` is missing from the needs block.

I tried adding ```'intl:main'``` to the needs block:
```
needs: [
  'intl:main', 'locale:en-GB',
  'helper:format-message', 'helper:intl-get'
]
```
Which also resulted in an exception:
```TypeError: Attempting to register an unknown factory: `intl:main````.

After digging through the ember-intl source I noticed that the ember-intl initializer sets up the intl service as ```intl:main``` instead of ```service:intl```. Trying to inject ```service:intl``` in the needs block doesn't work either.

My best guess is that initializers don't run in a (module) unit test, resulting in ```intl:main``` never being registered on the container/app. Because the ```intl-get``` helper injects ```intl:main``` rather than ```service:intl```, adding ```service:intl``` to the test's need block won't do anything.

At the moment, I don't even care what format-message/intl-get renders, stubbing out whatever ```format-message``` and/or ```intl-get``` needs would work just fine for me as well, I just want to be able to render the component's template without exceptions. (I just don't know how to do this)

My actual question(s):
* Am I doing something wrong?
* Is there any documentation that I missed that explains how to do this/make it work?
* If I'm not doing anything wrong, is there a way to work around this (eg. stubbing ```intl``` on ```intl-get```)?

Any answers or pointers in the right direction would be greatly appreciated!

**Comment by jasonmit** [comment]
I will update the docs tonight.  

I've been meaning to add examples around unit testing views utilitizing intl helpers.  We do it in our unit tests, most of the logic resides in module-for-intl

**Comment by jasonmit** [comment]
Sorry, on mobile version and fat fingered :)

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/pull/77 will resolve this.  Feel free to test the branch out and follow the docs to make sure I did not forget anything.

**Comment by mordack** [comment]
Thanks for the quick response! I'm currently using the #77 branch and trying to write a working unit test, but I'm still struggling.
I had to slightly change the ```setup()``` hook (setup isn't being called with ```container``` as an argument, though I'm using ember-mocha instead of ember-qunit, which might be the reason):

```
needs: [
  'service:intl',
  'helper:format-message', 'helper:intl-get',
  'locale:en-GB',
  'formatter:format-message'
],
setup: function() {
  registerIntl(this.container);
  var intl = this.container.lookup('service:intl');
  intl.set('locales', 'en-GB');
}
```

Using the #77 branch and the testing documentation, this is the exception that I get: 
```TypeError: Cannot read property 'IntlAdapter' of undefined```, pointing to [this](https://github.com/yahoo/ember-intl/blob/unit-testing/addon/services/intl.js#L49) line, telling me that app isn't properly injected into ```service:intl```.

I'm not entirely sure if this is an ember-intl issue, because I'm not using ember-qunit, but ember-mocha (maybe the ember-mocha test helpers don't expose ```application:main``` on the container, but that seems kinda strange).

**Comment by jasonmit** [comment]
> Using the #77 branch and the testing documentation, this is the exception that I get: 
> TypeError: Cannot read property 'IntlAdapter' of undefined, pointing to this line, telling me that app isn't properly injected into service:intl.

That's saying that app wasn't created from the `container.lookup` above it.  I haven't run into this, but my test didn't cover format-message so I'll switch my example to that since it's a more complicated test and probably the most common.

Do you have a branch anywhere that I can debug against?  I'll try and dig into ember-mocha to see why they're not registering `application:main`.

Thanks :+1:

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/commit/a8bcb5926beabd7897737b524b4d65d695b82083 may resolve the app being undefined.  I haven't worked through the code path for format-message testing, will verify this fixes it tonight for unit tests.

**Comment by mordack** [comment]
After updating the addon, the test was still failing, but with a different message, the stack trace pointing [here](https://github.com/yahoo/ember-intl/blob/unit-testing/addon/services/intl.js#L192):
```
TypeError: Cannot read property 'findTranslation' of undefined
```
Adapter was null, so I added ```adapter:-intl-adapter``` to the needs block and finally my test passed (just rendering the template).

(template)
```{{format-message (intl-get "messages.welcome") firstName=user.firstName lastName=user.lastName}}```

I added another test to verify if the formatted message was correct, but I got faillure:
```
AssertionError: expected '\nError: format-message requires a single unname argument. {{format-message value}}\n' to include 'FirstName'
```
It seems that ```intl-get``` returns nothing when running it in the unit test, I didn't get anything further than that.
I created a [sample project](https://github.com/mordack/format-message-unittest) with a sample component that uses ```format-message``` and ```intl-get``` with the failing test. I hope this gives you the info you need to dig any further.

Thanks a lot!

**Comment by jasonmit** [comment]
@mordack, changes are in.  

In your repo/sample app just remove the `adapter:-intl-adapter` in your `needs` array after pulling in the lasted on `unit-testing` and your tests should be passing.

**Comment by mordack** [comment]
@jasonmit, everything is working fine in our project with these changes, nothing breaks! :grin:
We'll be using this branch until it is merged and published to npm.

Thanks again for all the effort!

**Comment by jasonmit** [comment]
@mordack I just merged into master.  

I'm holding off on versioning 1.3.0, I have a few more changes I like to make for this release.  Mainly, dropping support for handlebars in favor of just htmlbars.

You'll be better off pointing to the last commit SHA (8e107e18fe7c6f23832953ce2a8100aa4d245727) instead of the feature branch.   Less likely to break your things when I remove the branch :)

**Comment by jasonmit** [comment]
@mordack my PR https://github.com/yahoo/ember-intl/pull/81 removing handlebar support in favor of just supporting htmlbars going forward eliminates the need to needs the format helpers.
