### ISSUE TITLE
intl-get template helper now returns an object instead of just the message string

### ISSUE THREAD

**Issue by terryroe** [yahoo/ember-intl#84]
We were using intl-get in templates like so:
```
{{intl-get 'messages.key.otherKey'}}
```
and it would return the message string.

It appears that this no longer works and intl-get returns an object.  We now have to change all our code from above to something like this:
```
{{format-message (intl-get 'messages.key.otherKey')}}
```
Was the first example above an intended use of intl-get?  Or was it always supposed to be used with format-message?

**Comment by jasonmit** [comment]
Correct, `intl-get` returns an object with a property `translation` and `locale`, where the translation derived from.  This is to tell the downstream format-message which locale to pass through to the format functions.

What is the use case for using `intl-get` within your templates outside of format-message/format-html-message?

**Comment by terryroe** [comment]
Jason,

We'd discovered that intl-get "worked" without using format-message.  It wasn't clear that you "had" to use format-message.  The docs didn't really say.  Now they do, but it's still not quite clear.  Here's the line that mentions it, but the wording of the line doesn't make it as obvious as I think it could:  "Will return the message from the current locale, or locale explicitly passed as an argument, message object."

So, it looks like we were using it in an unexpected way, and we just need to do it the correct way with format-message.

Thanks for your help.

TR

**Comment by jasonmit** [comment]
Leaving this opened for now to update the docs to be more clear.

Thanks for the good feedback

**Comment by al3x-edge** [comment]
Ran into this after update, but simple fix for us.  We were using just intl-get to output placeholders in select elements but recently started getting `[object Object]`.

For those who may not know, simply nested the sub-expression further:

```hbs
{{ember-selectize
    content=foo
    selection=bar
    placeholder=(format-message (intl-get "messages.global.selectPrompt"))}}
```
