### ISSUE TITLE
format-message boundProperty

### ISSUE THREAD

**Issue by al3x-edge** [yahoo/ember-intl#87]
There is an example with boundProperty is the readme for formatMessage but I've been unable to get it to work. Currently have a desire to change text within a couple buttons / headings. I could do it with `{{if}}` statements but just saw this and it's just as easy for me to change the message value to look up inside the controller.  Just looking for clarification on it's use. Looks like it needs the actual translation object, but I can't seem to track down the way to pull translations using `this.intl` (injected).

```hbs
{{format-message boundProperty
    name='Jason'
    numPhotos=num
    takenDate=yesterday}}
```

**Comment by caridy** [comment]
@al3x-edge in the example, `boundProperty` should have the value of the message, which is:

```
boundProperty === `You have {numPhotos, plural,
    =0 {no photos.}
    =1 {one photo.}
    other {# photos.}}`
```

The other option is to use the lookup helper `intl-get`, which will simply try to find the message value by key, which is the recommended way.

**Comment by al3x-edge** [comment]
@caridy Thanks for the answer -- Just as a follow up -- Is there a way to get the value of the message in a controller assuming it's injected?

**Comment by jasonmit** [comment]
> Is there a way to get the value of the message in a controller assuming it's injected?

You want to resolve a translation key to a translation message from a computed property on your controller?

**Comment by jasonmit** [comment]
@al3x-edge your last question might also be related to https://github.com/yahoo/ember-intl/issues/89

Let me know

**Comment by al3x-edge** [comment]
Thanks for the reference to #89 -- When asking the question, that is what I was looking for once the boundProperty didn't work. I'll keep this as reference.

Originally tried the second approach with setting a lookupString but was getting errors for some reason.  Recently updated all dependencies though -- not sure if something took or I just did it right the second time around -- and everything is fine.

Thanks for the help (@jasonmit / @caridy ). Greatly appreciated.
