### ISSUE TITLE
Road to 2.0.0

### ISSUE THREAD

**Issue by jasonmit** [yahoo/ember-intl#88]
### Incomplete
* [ ] Reverse the argument behavior of format-message
  * [ ] `{{format-message 'path.to.foo.bar'}}`
  * [ ] `{{format-message (icu '{{population, number, integer} as of {census_date, date, long}}')}}`
* [ ] Warn with message when intl-get is passed a key that is not found (https://github.com/yahoo/ember-intl/issues/107)
* [ ] ember-browserify the intl deps
* [ ] Provide a migration document with thorough instructions explaining upgrade path for breaking changes.

### Completed
* [x] Move format message into its own formatter
  * [x] Move the `format` computed prop out of service (mostly complete, format-message is last one)
* [x] Remove `defaultLocale`.  Instead, declared in env configuration (the same config evaluated at build time)
* [x] leverage instance-initializer for injecting instead of initializer
* [x] Tests failing due to new addition of `registry` in the container.  Will require changes to `moduleForIntl`
* [x] YAML translation file support
  * JSON translations are already supported, I'd like to support both for 2.0
* [x] When a translation is merged in from the default locale's translation file, throw a console warning at build time with the key(s) missing (mostly done, needs verifying for edge cases)
* [x] BREAKING: Translations now hang off `translations` (root folder) instead of `app/locales`
  * Allows to easier side-loading of translations
  * Reduces confusion between the three terms: locale, cldr, message/translation
  * Part of https://github.com/yahoo/ember-intl/issues/67
  * Commit: https://github.com/yahoo/ember-intl/commit/dd8b808e2824da59011cde3c1f7f59b6afb272f5
* [x] Automatically merge application default locale to all translations at build time
  * Configuration of default locale is defined in EmberApp within `config/environment`
  * Reduces confusion around fallback/default locale logic
  * Part of https://github.com/yahoo/ember-intl/issues/67 
* [x] BREAKING: Translation files can be in two formats, json and yaml, instead of ES6 modules
  * [x] JSON supported
  * Allows for easier third-party service serving translation assets
  * Commit: https://github.com/yahoo/ember-intl/commit/411ea11242611eba1467e6edd5b2751b0ce3a9dc
* [x] BREAKING: Translation modules no longer contain `messages` object.  All translations hang off the exported parent object by default

### Other
* [x] Move formatting logic out of service and into formatters.  This will thin the service, and the service will simply proxy to the formatters
* [x] Remove support for 1.9 (Handlebars)
* [x] BREAKING: Intl service is now only injected via `Ember.inject.service`, no longer automatic as it's seldom needed and Ember now makes it convenient to inject services
* [x] ES6-ify

**Comment by jasonmit** [comment]
Updated to reflected the YAML translation format proposal

/cc @ericf

**Comment by al3x-edge** [comment]
@jasonmit Is it possible to get out a beta1 before we complete some of the icu / path switching?

Trying to avoid our team getting a surprise at some point. Sadly we are still tracking this branch (/sadpanda) and then in beta2 release the switch?
