### ISSUE TITLE
Get Translation in JS Files with Parameters

### ISSUE THREAD

**Issue by svox1** [yahoo/ember-intl#89]
Hi,

I use Ember-CLI 0.2.1 and Ember 1.13.0-Canary.
I need the translation in a Controller.

How can I translate my strings with parameters?

I have read this:
https://github.com/yahoo/ember-intl/issues/60

`this.intl.getTranslation(key)`

But:
1. I get a Promise Object but I need the result as a String in a for-loop
2. How can I get the translation with Parameters? Like this:
`{{format-message (intl-get "messages.photos")
        name=name
        numPhotos=numPhotos
        takenDate=takenDate}}`

Is there anyway? Or have I still use `Ember.String.loc` for my translation?

Regards

**Comment by jasonmit** [comment]
> I get a Promise Object but I need the result as a String in a for-loop

Can you explain what you're doing?  Maybe I can offer up a solution but here is what I have that should work.

```js
export default Ember.Controller.extend({
  intl: Ember.inject.service(),
  actions: {
    doSomething: function () {
      var intl = this.get('intl');
      intl.getTranslation('foo.bar').then(function (result) {
         // not sure what version of ember-intl you are using
         // so it's either `result` or `translation`
         intl.formatMessage(result.translation || result.content, {
           name='Name'
           numPhotos=1000
           takenDate=new Date()
         }, {
           locales: result.locale
         })
      }.bind(this));
    }
  }
})
```

**Comment by svox1** [comment]
Thanks for the quick response.

Currently I have a loop like:
```javascript
myList: function() {
    return this.get('model').map(function(itemData) {
            var message = '';
            switch(itemData.get('type')) {
                case 'point':
                    message = '+' + itemData.get('value') + ' ' + itemData.get('message');
                    break;

               case 'playerJoined':
                    isMessage = true;
                    message = 'Joined the game';
                    break;

                 case 'playerLeft':
                    message = '"' + itemData.get('message') + '" has left the game';
                    break; 

                 case 'settingPointChanged':
                    message = 'Edit Settingpoint: ' + itemData.get('message') + '<br/>New Point: +' + itemData.get('value');
                    break;

                //......
            }
      }
}
```
And many more messages with different types and messages. This message I want to localized. And this is where Iam need a method that is returning a simple Object or String with paramters.

**Comment by jasonmit** [comment]
This branch supports your use-case of `findTranslation` returning a simple object: https://github.com/yahoo/ember-intl/tree/2.0

The returned object contains two properties: `content` (your translation string) and `locale` where the translation came from.

Notable changes needed in order to port your app to use this branch:
* Move your translations from /app/locales to /translations (outside of app folder)
* Your translation files should now be json files, if you need an example just look at the dummy app: 
https://github.com/yahoo/ember-intl/tree/2.0/tests/dummy
* Your config/environment should look something similar to:

```js
module.exports = function(environment) {
  var ENV = {
    intl: {
      defaultLocale: 'en-us', // your default locale
      outputPath: 'app/translations',
      inputPath: 'translations'
   }
 }
 return ENV;
}
```

This will hopefully be released in a few weeks.  If this works for you, I would point your package.json to a SHA rather than the branch name as I'll be iterating on this further and do not want to break your app :)

**Comment by svox1** [comment]
Thanks again!

Thanks for the informations. Currently Iam in production mode. So its better to wait for the stable release as you say. 
Just a note, I have integrate format.js 1.2.1 in my ember-cli 0.2.1 and ember 1.13-canary project and after that, all works fine in my browser (Chrome) but on my phone (iPhone) or with iOS - Emulator with cordova, I see the splashscreen and after that only a blank page. Nothing else with no error message.

But these only as a note because I didnt debug it and just removed the ember-intl.

Thanks for your work and sharing this project!

**Comment by jcope2013** [comment]
would this be safe or is there a formatHTMLMessage function that I should make instead?

```
   var intl = this.get('intl');
   return intl.getTranslation('messages.product.html.info').then(function (result) {
      var messageHtml = intl.formatMessage(result.translation || result.content, {
          product: 'Apple watch',
          price: 200
       }, {
          locales: result.locale
        });
    });
```

**Comment by jasonmit** [comment]
> Thanks for the question, turned out useful for me also, another question is would this be safe or is there a formatHtmlMessage function that I should make instead?

That's not safe, and I don't expose that as a method from the service to do it.  What you'll want to do is wrap that `messageHtml` in `Ember.String.htmlSafe`

**Comment by jasonmit** [comment]
> I see the splashscreen and after that only a blank page. Nothing else with no error message.

@svox1 You'll likely need to load the Intl polyfill, the README at the top covers instructions on how to do that.
