### ISSUE TITLE
Format dynamic properties

### ISSUE THREAD

**Issue by clubajax** [yahoo/ember-intl#90]
I can't figure out how to translate a string passed from the model in a dynamic template that could have various titles.
model.title = 'mytasks'
messages.mytasks 'My Tasks'
 
I've tried:
{{ format-message (intl-get model.title) }} 
and
{{ format-message model.title }}
and
{{ format-message messages[model.title] }}

I think maybe boundProperty might do something, but I can't find any documentation on how it works.

A satisfactory solution would be to translate the property in the model, but i can't figure out how to do translations in JavaScript (outside of a template)

**Comment by jasonmit** [comment]
Move messages.mytask to just mytask in your translation module and your first example, {{ format-message (intl-get model.title) }} should work.

Hanging props off messages is just a convention, and the default in the future will not include it since its led to confusion.

**Comment by clubajax** [comment]
I see now. Thanks.
