### ISSUE TITLE
Unable to use component property with intl-get

### ISSUE THREAD

**Issue by jpaas** [yahoo/ember-intl#93]
I have a custom component that I'm trying to assign resource key properties to, but the intl-get helper never works with them.

For example, my component (form-group) is used like this:

```javascript
  {{#form-group i18n-label='messages.attributes.user.email' }}
    {{input value=identification class='form-control input-lg'}}
  {{/form-group}}
```

The form-group template uses it like this:

```javascript
<label class="control-label">{{format-message (intl-get i18n-label)}}</label>
{{yield}}
```

This gives me the error `Assertion Failed: Cannot call get with undefined key.`

Is this a bug or am I doing something wrong?

**Comment by jasonmit** [comment]
I can't reproduce this:

```
// components/x-foo.js
import Ember from 'ember';

export default Ember.Component.extend();
```

```
// templates/components/x-foo.hbs
{{format-message (intl-get x-msg)}}

{{yield}}
```
```
// app.hbs
{{#x-foo x-msg='messages.product.html.info'}}
    something yielded
{{/x-foo}}
```

Are you able to push what you have to a branch somewhere?

**Comment by jpaas** [comment]
I can't reproduce it either anymore. I have a feeling that it went away when I upgraded something. Perhaps moving up to ember cli 0.2.3?
