### ISSUE TITLE
undefined is not a function (evaluating 'ember_intl.registerIntl(container)') when unit testing components

### ISSUE THREAD

**Issue by Azdaroth** [yahoo/ember-intl#95]
I want to unit test some components, but in all of them I get ```undefined is not a function (evaluating 'ember_intl.registerIntl(container)')``` when running tests. I followed the guides for unit testing, but can't get anywhere because of that error. Any idea why it happens?

**Comment by jasonmit** [comment]
I need more information, is this repo public for me to look at?

**Comment by Azdaroth** [comment]
Unfortunately not, it's a private project. I'll try to provide more details, so here's a very basic test:

```
import {
  moduleForComponent,
  test
} from 'ember-qunit';

import { registerIntl } from '../../../initializers/ember-intl';

moduleForComponent('some-component', {
  needs: [
    'formatter:format-number',
    'helper:format-number'
  ],

  setup: function () {
    var container = this.container || arguments[0];
    registerIntl(container);
  }
});

test('it renders', function(assert) {
  assert.expect(2);

  // creates the component instance
  var component = this.subject();
  assert.equal(component._state, 'preRender');

  // renders the component to the page
  this.render();
  assert.equal(component._state, 'inDOM');
});
``` 

and it fails with provided error. When I don't call `registerIntl(container);` I get `undefined is not an object (evaluating 'env.data')`.

I included `<script src="assets/intl/polyfill/Intl.complete.js"></script>` before all other scipt tags for tests, using ember-cli 0.2.2, updated ember-intl from 1.2.0 to 1.2.2, but still the problem persists.

**Comment by jasonmit** [comment]
What version of Ember?

**Comment by jasonmit** [comment]
I see the problem, you were reading the docs from #master which are not the same as the latest stable (1.2.2).  I'll work on a testing story for stable, but it will result in 1.3.0.  I'll update issue once complete.

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl/releases/tag/1.3.0 resolves this.

Please read the README from the 1.3.0 branch and not master, as it's slightly different (mainly just the adapter needs to be accounted for in the `needs`).

Example app with a basic test to validate it works: https://github.com/jasonmit/ember-intl-1.3.0-test-example

**Comment by Azdaroth** [comment]
Great, thanks! Updated to 1.3.0, changed tests and works like a charm now :).
