### ISSUE TITLE
Missing message Error

### ISSUE THREAD

**Issue by al3x-edge** [yahoo/ember-intl#96]
Haven't yet tried stable, but noticed on 2.0 branch _(Yup. I'm that guy)_ that the error message returned when there is no message available to translate is this: `findTranslation should return an object of instance 'IntlGetResult'`.

I noticed that there is an error below that, but it is never hit due to the assert exiting.
```js
if (typeof translation === 'undefined') {
    throw new Error('translation: `' + key + '` on locale(s): ' + locales.join(',') + ' was not found.');
}
```

I bring this up because when switching to 2.0 for the ability to get simple values returned during translation to output in HTML (not output -- supposed to be copied into clipboard).  I had the previous `messages.something.translateMe` which was throwing the assert and I couldn't figure it out until about 30 minutes later I remembered I took those out. 

Are we able to throw the assert after the error so that people are able to see they are missing the key to be translated also?

**Comment by jasonmit** [comment]
So you're using format-message and passing in a key that doesn't have a translation?  I'm unsure of the use-case there, can you explain more?  I am opened to changing this.

**Comment by al3x-edge** [comment]
@jasonmit Aye. Exactly.  Not really a use case; more of a helping users thing.  The assertion happens and then the error isn't displayed to users that their key was wrong -- Just that they should expect an `IntlGetResult` -- Kind of cryptic ya know?

**Comment by jasonmit** [comment]
:+1: I'll fix this

**Comment by jasonmit** [comment]
LGTM
