### ISSUE TITLE
Ember-Intl throws reference error in Safari

### ISSUE THREAD

**Issue by elwayman02** [yahoo/ember-intl#98]
```ReferenceError: Can't find variable: Intl```

As seen on my website: http://www.jordanhawker.com/posts/117025334671

I don't ever reference Intl as a global, so I am guessing it's an internal error.

https://github.com/elwayman02/jordan-hawker/search?utf8=%E2%9C%93&q=intl

I don't have a mac, so I can't reproduce and debug it.  Any ideas @jasonmit?

**Comment by jasonmit** [comment]
https://github.com/yahoo/ember-intl#installation
